// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: agynio/api/runners/v1/runners.proto

package runnersv1

import (
	context "context"
	v1 "github.com/agynio/runners/.gen/go/agynio/api/runner/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RunnersService_RegisterRunner_FullMethodName               = "/agynio.api.runners.v1.RunnersService/RegisterRunner"
	RunnersService_GetRunner_FullMethodName                    = "/agynio.api.runners.v1.RunnersService/GetRunner"
	RunnersService_ListRunners_FullMethodName                  = "/agynio.api.runners.v1.RunnersService/ListRunners"
	RunnersService_UpdateRunner_FullMethodName                 = "/agynio.api.runners.v1.RunnersService/UpdateRunner"
	RunnersService_DeleteRunner_FullMethodName                 = "/agynio.api.runners.v1.RunnersService/DeleteRunner"
	RunnersService_ValidateServiceToken_FullMethodName         = "/agynio.api.runners.v1.RunnersService/ValidateServiceToken"
	RunnersService_EnrollRunner_FullMethodName                 = "/agynio.api.runners.v1.RunnersService/EnrollRunner"
	RunnersService_CreateWorkload_FullMethodName               = "/agynio.api.runners.v1.RunnersService/CreateWorkload"
	RunnersService_UpdateWorkload_FullMethodName               = "/agynio.api.runners.v1.RunnersService/UpdateWorkload"
	RunnersService_UpdateWorkloadStatus_FullMethodName         = "/agynio.api.runners.v1.RunnersService/UpdateWorkloadStatus"
	RunnersService_TouchWorkload_FullMethodName                = "/agynio.api.runners.v1.RunnersService/TouchWorkload"
	RunnersService_DeleteWorkload_FullMethodName               = "/agynio.api.runners.v1.RunnersService/DeleteWorkload"
	RunnersService_GetWorkload_FullMethodName                  = "/agynio.api.runners.v1.RunnersService/GetWorkload"
	RunnersService_ListWorkloadsByThread_FullMethodName        = "/agynio.api.runners.v1.RunnersService/ListWorkloadsByThread"
	RunnersService_ListWorkloads_FullMethodName                = "/agynio.api.runners.v1.RunnersService/ListWorkloads"
	RunnersService_BatchUpdateWorkloadSampledAt_FullMethodName = "/agynio.api.runners.v1.RunnersService/BatchUpdateWorkloadSampledAt"
	RunnersService_StreamWorkloadLogs_FullMethodName           = "/agynio.api.runners.v1.RunnersService/StreamWorkloadLogs"
	RunnersService_CreateVolume_FullMethodName                 = "/agynio.api.runners.v1.RunnersService/CreateVolume"
	RunnersService_UpdateVolume_FullMethodName                 = "/agynio.api.runners.v1.RunnersService/UpdateVolume"
	RunnersService_GetVolume_FullMethodName                    = "/agynio.api.runners.v1.RunnersService/GetVolume"
	RunnersService_ListVolumes_FullMethodName                  = "/agynio.api.runners.v1.RunnersService/ListVolumes"
	RunnersService_ListVolumesByThread_FullMethodName          = "/agynio.api.runners.v1.RunnersService/ListVolumesByThread"
	RunnersService_BatchUpdateVolumeSampledAt_FullMethodName   = "/agynio.api.runners.v1.RunnersService/BatchUpdateVolumeSampledAt"
)

// RunnersServiceClient is the client API for RunnersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RunnersService manages runners and their workload state.
type RunnersServiceClient interface {
	// --- Runner management ---
	RegisterRunner(ctx context.Context, in *RegisterRunnerRequest, opts ...grpc.CallOption) (*RegisterRunnerResponse, error)
	GetRunner(ctx context.Context, in *GetRunnerRequest, opts ...grpc.CallOption) (*GetRunnerResponse, error)
	ListRunners(ctx context.Context, in *ListRunnersRequest, opts ...grpc.CallOption) (*ListRunnersResponse, error)
	UpdateRunner(ctx context.Context, in *UpdateRunnerRequest, opts ...grpc.CallOption) (*UpdateRunnerResponse, error)
	DeleteRunner(ctx context.Context, in *DeleteRunnerRequest, opts ...grpc.CallOption) (*DeleteRunnerResponse, error)
	ValidateServiceToken(ctx context.Context, in *ValidateServiceTokenRequest, opts ...grpc.CallOption) (*ValidateServiceTokenResponse, error)
	EnrollRunner(ctx context.Context, in *EnrollRunnerRequest, opts ...grpc.CallOption) (*EnrollRunnerResponse, error)
	// --- Workload state ---
	CreateWorkload(ctx context.Context, in *CreateWorkloadRequest, opts ...grpc.CallOption) (*CreateWorkloadResponse, error)
	UpdateWorkload(ctx context.Context, in *UpdateWorkloadRequest, opts ...grpc.CallOption) (*UpdateWorkloadResponse, error)
	UpdateWorkloadStatus(ctx context.Context, in *UpdateWorkloadStatusRequest, opts ...grpc.CallOption) (*UpdateWorkloadStatusResponse, error)
	TouchWorkload(ctx context.Context, in *TouchWorkloadRequest, opts ...grpc.CallOption) (*TouchWorkloadResponse, error)
	DeleteWorkload(ctx context.Context, in *DeleteWorkloadRequest, opts ...grpc.CallOption) (*DeleteWorkloadResponse, error)
	GetWorkload(ctx context.Context, in *GetWorkloadRequest, opts ...grpc.CallOption) (*GetWorkloadResponse, error)
	ListWorkloadsByThread(ctx context.Context, in *ListWorkloadsByThreadRequest, opts ...grpc.CallOption) (*ListWorkloadsByThreadResponse, error)
	ListWorkloads(ctx context.Context, in *ListWorkloadsRequest, opts ...grpc.CallOption) (*ListWorkloadsResponse, error)
	BatchUpdateWorkloadSampledAt(ctx context.Context, in *BatchUpdateWorkloadSampledAtRequest, opts ...grpc.CallOption) (*BatchUpdateWorkloadSampledAtResponse, error)
	// --- Workload logs ---
	StreamWorkloadLogs(ctx context.Context, in *v1.StreamWorkloadLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[v1.StreamWorkloadLogsResponse], error)
	// --- Volume state ---
	CreateVolume(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*CreateVolumeResponse, error)
	UpdateVolume(ctx context.Context, in *UpdateVolumeRequest, opts ...grpc.CallOption) (*UpdateVolumeResponse, error)
	GetVolume(ctx context.Context, in *GetVolumeRequest, opts ...grpc.CallOption) (*GetVolumeResponse, error)
	ListVolumes(ctx context.Context, in *ListVolumesRequest, opts ...grpc.CallOption) (*ListVolumesResponse, error)
	ListVolumesByThread(ctx context.Context, in *ListVolumesByThreadRequest, opts ...grpc.CallOption) (*ListVolumesByThreadResponse, error)
	BatchUpdateVolumeSampledAt(ctx context.Context, in *BatchUpdateVolumeSampledAtRequest, opts ...grpc.CallOption) (*BatchUpdateVolumeSampledAtResponse, error)
}

type runnersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRunnersServiceClient(cc grpc.ClientConnInterface) RunnersServiceClient {
	return &runnersServiceClient{cc}
}

func (c *runnersServiceClient) RegisterRunner(ctx context.Context, in *RegisterRunnerRequest, opts ...grpc.CallOption) (*RegisterRunnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterRunnerResponse)
	err := c.cc.Invoke(ctx, RunnersService_RegisterRunner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnersServiceClient) GetRunner(ctx context.Context, in *GetRunnerRequest, opts ...grpc.CallOption) (*GetRunnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRunnerResponse)
	err := c.cc.Invoke(ctx, RunnersService_GetRunner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnersServiceClient) ListRunners(ctx context.Context, in *ListRunnersRequest, opts ...grpc.CallOption) (*ListRunnersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRunnersResponse)
	err := c.cc.Invoke(ctx, RunnersService_ListRunners_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnersServiceClient) UpdateRunner(ctx context.Context, in *UpdateRunnerRequest, opts ...grpc.CallOption) (*UpdateRunnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRunnerResponse)
	err := c.cc.Invoke(ctx, RunnersService_UpdateRunner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnersServiceClient) DeleteRunner(ctx context.Context, in *DeleteRunnerRequest, opts ...grpc.CallOption) (*DeleteRunnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRunnerResponse)
	err := c.cc.Invoke(ctx, RunnersService_DeleteRunner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnersServiceClient) ValidateServiceToken(ctx context.Context, in *ValidateServiceTokenRequest, opts ...grpc.CallOption) (*ValidateServiceTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateServiceTokenResponse)
	err := c.cc.Invoke(ctx, RunnersService_ValidateServiceToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnersServiceClient) EnrollRunner(ctx context.Context, in *EnrollRunnerRequest, opts ...grpc.CallOption) (*EnrollRunnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollRunnerResponse)
	err := c.cc.Invoke(ctx, RunnersService_EnrollRunner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnersServiceClient) CreateWorkload(ctx context.Context, in *CreateWorkloadRequest, opts ...grpc.CallOption) (*CreateWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWorkloadResponse)
	err := c.cc.Invoke(ctx, RunnersService_CreateWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnersServiceClient) UpdateWorkload(ctx context.Context, in *UpdateWorkloadRequest, opts ...grpc.CallOption) (*UpdateWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateWorkloadResponse)
	err := c.cc.Invoke(ctx, RunnersService_UpdateWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnersServiceClient) UpdateWorkloadStatus(ctx context.Context, in *UpdateWorkloadStatusRequest, opts ...grpc.CallOption) (*UpdateWorkloadStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateWorkloadStatusResponse)
	err := c.cc.Invoke(ctx, RunnersService_UpdateWorkloadStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnersServiceClient) TouchWorkload(ctx context.Context, in *TouchWorkloadRequest, opts ...grpc.CallOption) (*TouchWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TouchWorkloadResponse)
	err := c.cc.Invoke(ctx, RunnersService_TouchWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnersServiceClient) DeleteWorkload(ctx context.Context, in *DeleteWorkloadRequest, opts ...grpc.CallOption) (*DeleteWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWorkloadResponse)
	err := c.cc.Invoke(ctx, RunnersService_DeleteWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnersServiceClient) GetWorkload(ctx context.Context, in *GetWorkloadRequest, opts ...grpc.CallOption) (*GetWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkloadResponse)
	err := c.cc.Invoke(ctx, RunnersService_GetWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnersServiceClient) ListWorkloadsByThread(ctx context.Context, in *ListWorkloadsByThreadRequest, opts ...grpc.CallOption) (*ListWorkloadsByThreadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkloadsByThreadResponse)
	err := c.cc.Invoke(ctx, RunnersService_ListWorkloadsByThread_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnersServiceClient) ListWorkloads(ctx context.Context, in *ListWorkloadsRequest, opts ...grpc.CallOption) (*ListWorkloadsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkloadsResponse)
	err := c.cc.Invoke(ctx, RunnersService_ListWorkloads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnersServiceClient) BatchUpdateWorkloadSampledAt(ctx context.Context, in *BatchUpdateWorkloadSampledAtRequest, opts ...grpc.CallOption) (*BatchUpdateWorkloadSampledAtResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchUpdateWorkloadSampledAtResponse)
	err := c.cc.Invoke(ctx, RunnersService_BatchUpdateWorkloadSampledAt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnersServiceClient) StreamWorkloadLogs(ctx context.Context, in *v1.StreamWorkloadLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[v1.StreamWorkloadLogsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RunnersService_ServiceDesc.Streams[0], RunnersService_StreamWorkloadLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[v1.StreamWorkloadLogsRequest, v1.StreamWorkloadLogsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RunnersService_StreamWorkloadLogsClient = grpc.ServerStreamingClient[v1.StreamWorkloadLogsResponse]

func (c *runnersServiceClient) CreateVolume(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*CreateVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVolumeResponse)
	err := c.cc.Invoke(ctx, RunnersService_CreateVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnersServiceClient) UpdateVolume(ctx context.Context, in *UpdateVolumeRequest, opts ...grpc.CallOption) (*UpdateVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateVolumeResponse)
	err := c.cc.Invoke(ctx, RunnersService_UpdateVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnersServiceClient) GetVolume(ctx context.Context, in *GetVolumeRequest, opts ...grpc.CallOption) (*GetVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVolumeResponse)
	err := c.cc.Invoke(ctx, RunnersService_GetVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnersServiceClient) ListVolumes(ctx context.Context, in *ListVolumesRequest, opts ...grpc.CallOption) (*ListVolumesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVolumesResponse)
	err := c.cc.Invoke(ctx, RunnersService_ListVolumes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnersServiceClient) ListVolumesByThread(ctx context.Context, in *ListVolumesByThreadRequest, opts ...grpc.CallOption) (*ListVolumesByThreadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVolumesByThreadResponse)
	err := c.cc.Invoke(ctx, RunnersService_ListVolumesByThread_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnersServiceClient) BatchUpdateVolumeSampledAt(ctx context.Context, in *BatchUpdateVolumeSampledAtRequest, opts ...grpc.CallOption) (*BatchUpdateVolumeSampledAtResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchUpdateVolumeSampledAtResponse)
	err := c.cc.Invoke(ctx, RunnersService_BatchUpdateVolumeSampledAt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunnersServiceServer is the server API for RunnersService service.
// All implementations should embed UnimplementedRunnersServiceServer
// for forward compatibility.
//
// RunnersService manages runners and their workload state.
type RunnersServiceServer interface {
	// --- Runner management ---
	RegisterRunner(context.Context, *RegisterRunnerRequest) (*RegisterRunnerResponse, error)
	GetRunner(context.Context, *GetRunnerRequest) (*GetRunnerResponse, error)
	ListRunners(context.Context, *ListRunnersRequest) (*ListRunnersResponse, error)
	UpdateRunner(context.Context, *UpdateRunnerRequest) (*UpdateRunnerResponse, error)
	DeleteRunner(context.Context, *DeleteRunnerRequest) (*DeleteRunnerResponse, error)
	ValidateServiceToken(context.Context, *ValidateServiceTokenRequest) (*ValidateServiceTokenResponse, error)
	EnrollRunner(context.Context, *EnrollRunnerRequest) (*EnrollRunnerResponse, error)
	// --- Workload state ---
	CreateWorkload(context.Context, *CreateWorkloadRequest) (*CreateWorkloadResponse, error)
	UpdateWorkload(context.Context, *UpdateWorkloadRequest) (*UpdateWorkloadResponse, error)
	UpdateWorkloadStatus(context.Context, *UpdateWorkloadStatusRequest) (*UpdateWorkloadStatusResponse, error)
	TouchWorkload(context.Context, *TouchWorkloadRequest) (*TouchWorkloadResponse, error)
	DeleteWorkload(context.Context, *DeleteWorkloadRequest) (*DeleteWorkloadResponse, error)
	GetWorkload(context.Context, *GetWorkloadRequest) (*GetWorkloadResponse, error)
	ListWorkloadsByThread(context.Context, *ListWorkloadsByThreadRequest) (*ListWorkloadsByThreadResponse, error)
	ListWorkloads(context.Context, *ListWorkloadsRequest) (*ListWorkloadsResponse, error)
	BatchUpdateWorkloadSampledAt(context.Context, *BatchUpdateWorkloadSampledAtRequest) (*BatchUpdateWorkloadSampledAtResponse, error)
	// --- Workload logs ---
	StreamWorkloadLogs(*v1.StreamWorkloadLogsRequest, grpc.ServerStreamingServer[v1.StreamWorkloadLogsResponse]) error
	// --- Volume state ---
	CreateVolume(context.Context, *CreateVolumeRequest) (*CreateVolumeResponse, error)
	UpdateVolume(context.Context, *UpdateVolumeRequest) (*UpdateVolumeResponse, error)
	GetVolume(context.Context, *GetVolumeRequest) (*GetVolumeResponse, error)
	ListVolumes(context.Context, *ListVolumesRequest) (*ListVolumesResponse, error)
	ListVolumesByThread(context.Context, *ListVolumesByThreadRequest) (*ListVolumesByThreadResponse, error)
	BatchUpdateVolumeSampledAt(context.Context, *BatchUpdateVolumeSampledAtRequest) (*BatchUpdateVolumeSampledAtResponse, error)
}

// UnimplementedRunnersServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunnersServiceServer struct{}

func (UnimplementedRunnersServiceServer) RegisterRunner(context.Context, *RegisterRunnerRequest) (*RegisterRunnerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterRunner not implemented")
}
func (UnimplementedRunnersServiceServer) GetRunner(context.Context, *GetRunnerRequest) (*GetRunnerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRunner not implemented")
}
func (UnimplementedRunnersServiceServer) ListRunners(context.Context, *ListRunnersRequest) (*ListRunnersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRunners not implemented")
}
func (UnimplementedRunnersServiceServer) UpdateRunner(context.Context, *UpdateRunnerRequest) (*UpdateRunnerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRunner not implemented")
}
func (UnimplementedRunnersServiceServer) DeleteRunner(context.Context, *DeleteRunnerRequest) (*DeleteRunnerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRunner not implemented")
}
func (UnimplementedRunnersServiceServer) ValidateServiceToken(context.Context, *ValidateServiceTokenRequest) (*ValidateServiceTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateServiceToken not implemented")
}
func (UnimplementedRunnersServiceServer) EnrollRunner(context.Context, *EnrollRunnerRequest) (*EnrollRunnerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrollRunner not implemented")
}
func (UnimplementedRunnersServiceServer) CreateWorkload(context.Context, *CreateWorkloadRequest) (*CreateWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWorkload not implemented")
}
func (UnimplementedRunnersServiceServer) UpdateWorkload(context.Context, *UpdateWorkloadRequest) (*UpdateWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWorkload not implemented")
}
func (UnimplementedRunnersServiceServer) UpdateWorkloadStatus(context.Context, *UpdateWorkloadStatusRequest) (*UpdateWorkloadStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWorkloadStatus not implemented")
}
func (UnimplementedRunnersServiceServer) TouchWorkload(context.Context, *TouchWorkloadRequest) (*TouchWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TouchWorkload not implemented")
}
func (UnimplementedRunnersServiceServer) DeleteWorkload(context.Context, *DeleteWorkloadRequest) (*DeleteWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWorkload not implemented")
}
func (UnimplementedRunnersServiceServer) GetWorkload(context.Context, *GetWorkloadRequest) (*GetWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkload not implemented")
}
func (UnimplementedRunnersServiceServer) ListWorkloadsByThread(context.Context, *ListWorkloadsByThreadRequest) (*ListWorkloadsByThreadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkloadsByThread not implemented")
}
func (UnimplementedRunnersServiceServer) ListWorkloads(context.Context, *ListWorkloadsRequest) (*ListWorkloadsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkloads not implemented")
}
func (UnimplementedRunnersServiceServer) BatchUpdateWorkloadSampledAt(context.Context, *BatchUpdateWorkloadSampledAtRequest) (*BatchUpdateWorkloadSampledAtResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchUpdateWorkloadSampledAt not implemented")
}
func (UnimplementedRunnersServiceServer) StreamWorkloadLogs(*v1.StreamWorkloadLogsRequest, grpc.ServerStreamingServer[v1.StreamWorkloadLogsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamWorkloadLogs not implemented")
}
func (UnimplementedRunnersServiceServer) CreateVolume(context.Context, *CreateVolumeRequest) (*CreateVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVolume not implemented")
}
func (UnimplementedRunnersServiceServer) UpdateVolume(context.Context, *UpdateVolumeRequest) (*UpdateVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateVolume not implemented")
}
func (UnimplementedRunnersServiceServer) GetVolume(context.Context, *GetVolumeRequest) (*GetVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVolume not implemented")
}
func (UnimplementedRunnersServiceServer) ListVolumes(context.Context, *ListVolumesRequest) (*ListVolumesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVolumes not implemented")
}
func (UnimplementedRunnersServiceServer) ListVolumesByThread(context.Context, *ListVolumesByThreadRequest) (*ListVolumesByThreadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVolumesByThread not implemented")
}
func (UnimplementedRunnersServiceServer) BatchUpdateVolumeSampledAt(context.Context, *BatchUpdateVolumeSampledAtRequest) (*BatchUpdateVolumeSampledAtResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchUpdateVolumeSampledAt not implemented")
}
func (UnimplementedRunnersServiceServer) testEmbeddedByValue() {}

// UnsafeRunnersServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunnersServiceServer will
// result in compilation errors.
type UnsafeRunnersServiceServer interface {
	mustEmbedUnimplementedRunnersServiceServer()
}

func RegisterRunnersServiceServer(s grpc.ServiceRegistrar, srv RunnersServiceServer) {
	// If the following call panics, it indicates UnimplementedRunnersServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RunnersService_ServiceDesc, srv)
}

func _RunnersService_RegisterRunner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRunnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersServiceServer).RegisterRunner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersService_RegisterRunner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersServiceServer).RegisterRunner(ctx, req.(*RegisterRunnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnersService_GetRunner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersServiceServer).GetRunner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersService_GetRunner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersServiceServer).GetRunner(ctx, req.(*GetRunnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnersService_ListRunners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRunnersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersServiceServer).ListRunners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersService_ListRunners_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersServiceServer).ListRunners(ctx, req.(*ListRunnersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnersService_UpdateRunner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRunnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersServiceServer).UpdateRunner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersService_UpdateRunner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersServiceServer).UpdateRunner(ctx, req.(*UpdateRunnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnersService_DeleteRunner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRunnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersServiceServer).DeleteRunner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersService_DeleteRunner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersServiceServer).DeleteRunner(ctx, req.(*DeleteRunnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnersService_ValidateServiceToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateServiceTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersServiceServer).ValidateServiceToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersService_ValidateServiceToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersServiceServer).ValidateServiceToken(ctx, req.(*ValidateServiceTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnersService_EnrollRunner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRunnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersServiceServer).EnrollRunner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersService_EnrollRunner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersServiceServer).EnrollRunner(ctx, req.(*EnrollRunnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnersService_CreateWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersServiceServer).CreateWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersService_CreateWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersServiceServer).CreateWorkload(ctx, req.(*CreateWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnersService_UpdateWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersServiceServer).UpdateWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersService_UpdateWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersServiceServer).UpdateWorkload(ctx, req.(*UpdateWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnersService_UpdateWorkloadStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWorkloadStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersServiceServer).UpdateWorkloadStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersService_UpdateWorkloadStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersServiceServer).UpdateWorkloadStatus(ctx, req.(*UpdateWorkloadStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnersService_TouchWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TouchWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersServiceServer).TouchWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersService_TouchWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersServiceServer).TouchWorkload(ctx, req.(*TouchWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnersService_DeleteWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersServiceServer).DeleteWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersService_DeleteWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersServiceServer).DeleteWorkload(ctx, req.(*DeleteWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnersService_GetWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersServiceServer).GetWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersService_GetWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersServiceServer).GetWorkload(ctx, req.(*GetWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnersService_ListWorkloadsByThread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkloadsByThreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersServiceServer).ListWorkloadsByThread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersService_ListWorkloadsByThread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersServiceServer).ListWorkloadsByThread(ctx, req.(*ListWorkloadsByThreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnersService_ListWorkloads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkloadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersServiceServer).ListWorkloads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersService_ListWorkloads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersServiceServer).ListWorkloads(ctx, req.(*ListWorkloadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnersService_BatchUpdateWorkloadSampledAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUpdateWorkloadSampledAtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersServiceServer).BatchUpdateWorkloadSampledAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersService_BatchUpdateWorkloadSampledAt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersServiceServer).BatchUpdateWorkloadSampledAt(ctx, req.(*BatchUpdateWorkloadSampledAtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnersService_StreamWorkloadLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(v1.StreamWorkloadLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RunnersServiceServer).StreamWorkloadLogs(m, &grpc.GenericServerStream[v1.StreamWorkloadLogsRequest, v1.StreamWorkloadLogsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RunnersService_StreamWorkloadLogsServer = grpc.ServerStreamingServer[v1.StreamWorkloadLogsResponse]

func _RunnersService_CreateVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersServiceServer).CreateVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersService_CreateVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersServiceServer).CreateVolume(ctx, req.(*CreateVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnersService_UpdateVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersServiceServer).UpdateVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersService_UpdateVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersServiceServer).UpdateVolume(ctx, req.(*UpdateVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnersService_GetVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersServiceServer).GetVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersService_GetVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersServiceServer).GetVolume(ctx, req.(*GetVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnersService_ListVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVolumesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersServiceServer).ListVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersService_ListVolumes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersServiceServer).ListVolumes(ctx, req.(*ListVolumesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnersService_ListVolumesByThread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVolumesByThreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersServiceServer).ListVolumesByThread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersService_ListVolumesByThread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersServiceServer).ListVolumesByThread(ctx, req.(*ListVolumesByThreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnersService_BatchUpdateVolumeSampledAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUpdateVolumeSampledAtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersServiceServer).BatchUpdateVolumeSampledAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersService_BatchUpdateVolumeSampledAt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersServiceServer).BatchUpdateVolumeSampledAt(ctx, req.(*BatchUpdateVolumeSampledAtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RunnersService_ServiceDesc is the grpc.ServiceDesc for RunnersService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunnersService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agynio.api.runners.v1.RunnersService",
	HandlerType: (*RunnersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterRunner",
			Handler:    _RunnersService_RegisterRunner_Handler,
		},
		{
			MethodName: "GetRunner",
			Handler:    _RunnersService_GetRunner_Handler,
		},
		{
			MethodName: "ListRunners",
			Handler:    _RunnersService_ListRunners_Handler,
		},
		{
			MethodName: "UpdateRunner",
			Handler:    _RunnersService_UpdateRunner_Handler,
		},
		{
			MethodName: "DeleteRunner",
			Handler:    _RunnersService_DeleteRunner_Handler,
		},
		{
			MethodName: "ValidateServiceToken",
			Handler:    _RunnersService_ValidateServiceToken_Handler,
		},
		{
			MethodName: "EnrollRunner",
			Handler:    _RunnersService_EnrollRunner_Handler,
		},
		{
			MethodName: "CreateWorkload",
			Handler:    _RunnersService_CreateWorkload_Handler,
		},
		{
			MethodName: "UpdateWorkload",
			Handler:    _RunnersService_UpdateWorkload_Handler,
		},
		{
			MethodName: "UpdateWorkloadStatus",
			Handler:    _RunnersService_UpdateWorkloadStatus_Handler,
		},
		{
			MethodName: "TouchWorkload",
			Handler:    _RunnersService_TouchWorkload_Handler,
		},
		{
			MethodName: "DeleteWorkload",
			Handler:    _RunnersService_DeleteWorkload_Handler,
		},
		{
			MethodName: "GetWorkload",
			Handler:    _RunnersService_GetWorkload_Handler,
		},
		{
			MethodName: "ListWorkloadsByThread",
			Handler:    _RunnersService_ListWorkloadsByThread_Handler,
		},
		{
			MethodName: "ListWorkloads",
			Handler:    _RunnersService_ListWorkloads_Handler,
		},
		{
			MethodName: "BatchUpdateWorkloadSampledAt",
			Handler:    _RunnersService_BatchUpdateWorkloadSampledAt_Handler,
		},
		{
			MethodName: "CreateVolume",
			Handler:    _RunnersService_CreateVolume_Handler,
		},
		{
			MethodName: "UpdateVolume",
			Handler:    _RunnersService_UpdateVolume_Handler,
		},
		{
			MethodName: "GetVolume",
			Handler:    _RunnersService_GetVolume_Handler,
		},
		{
			MethodName: "ListVolumes",
			Handler:    _RunnersService_ListVolumes_Handler,
		},
		{
			MethodName: "ListVolumesByThread",
			Handler:    _RunnersService_ListVolumesByThread_Handler,
		},
		{
			MethodName: "BatchUpdateVolumeSampledAt",
			Handler:    _RunnersService_BatchUpdateVolumeSampledAt_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamWorkloadLogs",
			Handler:       _RunnersService_StreamWorkloadLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agynio/api/runners/v1/runners.proto",
}
