// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agynio/api/runners/v1/runners.proto

package runnersv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunnerStatus int32

const (
	RunnerStatus_RUNNER_STATUS_UNSPECIFIED RunnerStatus = 0
	RunnerStatus_RUNNER_STATUS_PENDING     RunnerStatus = 1
	RunnerStatus_RUNNER_STATUS_ENROLLED    RunnerStatus = 2
	RunnerStatus_RUNNER_STATUS_OFFLINE     RunnerStatus = 3
)

// Enum value maps for RunnerStatus.
var (
	RunnerStatus_name = map[int32]string{
		0: "RUNNER_STATUS_UNSPECIFIED",
		1: "RUNNER_STATUS_PENDING",
		2: "RUNNER_STATUS_ENROLLED",
		3: "RUNNER_STATUS_OFFLINE",
	}
	RunnerStatus_value = map[string]int32{
		"RUNNER_STATUS_UNSPECIFIED": 0,
		"RUNNER_STATUS_PENDING":     1,
		"RUNNER_STATUS_ENROLLED":    2,
		"RUNNER_STATUS_OFFLINE":     3,
	}
)

func (x RunnerStatus) Enum() *RunnerStatus {
	p := new(RunnerStatus)
	*p = x
	return p
}

func (x RunnerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunnerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agynio_api_runners_v1_runners_proto_enumTypes[0].Descriptor()
}

func (RunnerStatus) Type() protoreflect.EnumType {
	return &file_agynio_api_runners_v1_runners_proto_enumTypes[0]
}

func (x RunnerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunnerStatus.Descriptor instead.
func (RunnerStatus) EnumDescriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{0}
}

type WorkloadStatus int32

const (
	WorkloadStatus_WORKLOAD_STATUS_UNSPECIFIED WorkloadStatus = 0
	WorkloadStatus_WORKLOAD_STATUS_STARTING    WorkloadStatus = 1
	WorkloadStatus_WORKLOAD_STATUS_RUNNING     WorkloadStatus = 2
	WorkloadStatus_WORKLOAD_STATUS_STOPPING    WorkloadStatus = 3
	WorkloadStatus_WORKLOAD_STATUS_STOPPED     WorkloadStatus = 4
	WorkloadStatus_WORKLOAD_STATUS_FAILED      WorkloadStatus = 5
)

// Enum value maps for WorkloadStatus.
var (
	WorkloadStatus_name = map[int32]string{
		0: "WORKLOAD_STATUS_UNSPECIFIED",
		1: "WORKLOAD_STATUS_STARTING",
		2: "WORKLOAD_STATUS_RUNNING",
		3: "WORKLOAD_STATUS_STOPPING",
		4: "WORKLOAD_STATUS_STOPPED",
		5: "WORKLOAD_STATUS_FAILED",
	}
	WorkloadStatus_value = map[string]int32{
		"WORKLOAD_STATUS_UNSPECIFIED": 0,
		"WORKLOAD_STATUS_STARTING":    1,
		"WORKLOAD_STATUS_RUNNING":     2,
		"WORKLOAD_STATUS_STOPPING":    3,
		"WORKLOAD_STATUS_STOPPED":     4,
		"WORKLOAD_STATUS_FAILED":      5,
	}
)

func (x WorkloadStatus) Enum() *WorkloadStatus {
	p := new(WorkloadStatus)
	*p = x
	return p
}

func (x WorkloadStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkloadStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agynio_api_runners_v1_runners_proto_enumTypes[1].Descriptor()
}

func (WorkloadStatus) Type() protoreflect.EnumType {
	return &file_agynio_api_runners_v1_runners_proto_enumTypes[1]
}

func (x WorkloadStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkloadStatus.Descriptor instead.
func (WorkloadStatus) EnumDescriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{1}
}

type ContainerRole int32

const (
	ContainerRole_CONTAINER_ROLE_UNSPECIFIED ContainerRole = 0
	ContainerRole_CONTAINER_ROLE_MAIN        ContainerRole = 1
	ContainerRole_CONTAINER_ROLE_SIDECAR     ContainerRole = 2
	ContainerRole_CONTAINER_ROLE_INIT        ContainerRole = 3
)

// Enum value maps for ContainerRole.
var (
	ContainerRole_name = map[int32]string{
		0: "CONTAINER_ROLE_UNSPECIFIED",
		1: "CONTAINER_ROLE_MAIN",
		2: "CONTAINER_ROLE_SIDECAR",
		3: "CONTAINER_ROLE_INIT",
	}
	ContainerRole_value = map[string]int32{
		"CONTAINER_ROLE_UNSPECIFIED": 0,
		"CONTAINER_ROLE_MAIN":        1,
		"CONTAINER_ROLE_SIDECAR":     2,
		"CONTAINER_ROLE_INIT":        3,
	}
)

func (x ContainerRole) Enum() *ContainerRole {
	p := new(ContainerRole)
	*p = x
	return p
}

func (x ContainerRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContainerRole) Descriptor() protoreflect.EnumDescriptor {
	return file_agynio_api_runners_v1_runners_proto_enumTypes[2].Descriptor()
}

func (ContainerRole) Type() protoreflect.EnumType {
	return &file_agynio_api_runners_v1_runners_proto_enumTypes[2]
}

func (x ContainerRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContainerRole.Descriptor instead.
func (ContainerRole) EnumDescriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{2}
}

type ContainerStatus int32

const (
	ContainerStatus_CONTAINER_STATUS_UNSPECIFIED ContainerStatus = 0
	ContainerStatus_CONTAINER_STATUS_RUNNING     ContainerStatus = 1
	ContainerStatus_CONTAINER_STATUS_TERMINATED  ContainerStatus = 2
	ContainerStatus_CONTAINER_STATUS_WAITING     ContainerStatus = 3
)

// Enum value maps for ContainerStatus.
var (
	ContainerStatus_name = map[int32]string{
		0: "CONTAINER_STATUS_UNSPECIFIED",
		1: "CONTAINER_STATUS_RUNNING",
		2: "CONTAINER_STATUS_TERMINATED",
		3: "CONTAINER_STATUS_WAITING",
	}
	ContainerStatus_value = map[string]int32{
		"CONTAINER_STATUS_UNSPECIFIED": 0,
		"CONTAINER_STATUS_RUNNING":     1,
		"CONTAINER_STATUS_TERMINATED":  2,
		"CONTAINER_STATUS_WAITING":     3,
	}
)

func (x ContainerStatus) Enum() *ContainerStatus {
	p := new(ContainerStatus)
	*p = x
	return p
}

func (x ContainerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContainerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agynio_api_runners_v1_runners_proto_enumTypes[3].Descriptor()
}

func (ContainerStatus) Type() protoreflect.EnumType {
	return &file_agynio_api_runners_v1_runners_proto_enumTypes[3]
}

func (x ContainerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContainerStatus.Descriptor instead.
func (ContainerStatus) EnumDescriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{3}
}

type EntityMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityMeta) Reset() {
	*x = EntityMeta{}
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityMeta) ProtoMessage() {}

func (x *EntityMeta) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityMeta.ProtoReflect.Descriptor instead.
func (*EntityMeta) Descriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{0}
}

func (x *EntityMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntityMeta) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *EntityMeta) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Runner struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Meta           *EntityMeta            `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OrganizationId *string                `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3,oneof" json:"organization_id,omitempty"`
	IdentityId     string                 `protobuf:"bytes,4,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	Status         RunnerStatus           `protobuf:"varint,5,opt,name=status,proto3,enum=agynio.api.runners.v1.RunnerStatus" json:"status,omitempty"`
	Labels         map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Per-runner OpenZiti service name (e.g. "runner-{id}")
	OpenzitiServiceName string `protobuf:"bytes,7,opt,name=openziti_service_name,json=openzitiServiceName,proto3" json:"openziti_service_name,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Runner) Reset() {
	*x = Runner{}
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Runner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Runner) ProtoMessage() {}

func (x *Runner) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Runner.ProtoReflect.Descriptor instead.
func (*Runner) Descriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{1}
}

func (x *Runner) GetMeta() *EntityMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Runner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Runner) GetOrganizationId() string {
	if x != nil && x.OrganizationId != nil {
		return *x.OrganizationId
	}
	return ""
}

func (x *Runner) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *Runner) GetStatus() RunnerStatus {
	if x != nil {
		return x.Status
	}
	return RunnerStatus_RUNNER_STATUS_UNSPECIFIED
}

func (x *Runner) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Runner) GetOpenzitiServiceName() string {
	if x != nil {
		return x.OpenzitiServiceName
	}
	return ""
}

type RegisterRunnerRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OrganizationId *string                `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3,oneof" json:"organization_id,omitempty"`
	Labels         map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterRunnerRequest) Reset() {
	*x = RegisterRunnerRequest{}
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRunnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRunnerRequest) ProtoMessage() {}

func (x *RegisterRunnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRunnerRequest.ProtoReflect.Descriptor instead.
func (*RegisterRunnerRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRunnerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRunnerRequest) GetOrganizationId() string {
	if x != nil && x.OrganizationId != nil {
		return *x.OrganizationId
	}
	return ""
}

func (x *RegisterRunnerRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type RegisterRunnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runner        *Runner                `protobuf:"bytes,1,opt,name=runner,proto3" json:"runner,omitempty"`
	ServiceToken  string                 `protobuf:"bytes,2,opt,name=service_token,json=serviceToken,proto3" json:"service_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRunnerResponse) Reset() {
	*x = RegisterRunnerResponse{}
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRunnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRunnerResponse) ProtoMessage() {}

func (x *RegisterRunnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRunnerResponse.ProtoReflect.Descriptor instead.
func (*RegisterRunnerResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterRunnerResponse) GetRunner() *Runner {
	if x != nil {
		return x.Runner
	}
	return nil
}

func (x *RegisterRunnerResponse) GetServiceToken() string {
	if x != nil {
		return x.ServiceToken
	}
	return ""
}

type GetRunnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunnerRequest) Reset() {
	*x = GetRunnerRequest{}
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunnerRequest) ProtoMessage() {}

func (x *GetRunnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunnerRequest.ProtoReflect.Descriptor instead.
func (*GetRunnerRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{4}
}

func (x *GetRunnerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRunnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runner        *Runner                `protobuf:"bytes,1,opt,name=runner,proto3" json:"runner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunnerResponse) Reset() {
	*x = GetRunnerResponse{}
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunnerResponse) ProtoMessage() {}

func (x *GetRunnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunnerResponse.ProtoReflect.Descriptor instead.
func (*GetRunnerResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{5}
}

func (x *GetRunnerResponse) GetRunner() *Runner {
	if x != nil {
		return x.Runner
	}
	return nil
}

type ListRunnersRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PageSize       int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken      string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	OrganizationId *string                `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3,oneof" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListRunnersRequest) Reset() {
	*x = ListRunnersRequest{}
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunnersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunnersRequest) ProtoMessage() {}

func (x *ListRunnersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunnersRequest.ProtoReflect.Descriptor instead.
func (*ListRunnersRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{6}
}

func (x *ListRunnersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRunnersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListRunnersRequest) GetOrganizationId() string {
	if x != nil && x.OrganizationId != nil {
		return *x.OrganizationId
	}
	return ""
}

type ListRunnersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runners       []*Runner              `protobuf:"bytes,1,rep,name=runners,proto3" json:"runners,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunnersResponse) Reset() {
	*x = ListRunnersResponse{}
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunnersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunnersResponse) ProtoMessage() {}

func (x *ListRunnersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunnersResponse.ProtoReflect.Descriptor instead.
func (*ListRunnersResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{7}
}

func (x *ListRunnersResponse) GetRunners() []*Runner {
	if x != nil {
		return x.Runners
	}
	return nil
}

func (x *ListRunnersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateRunnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRunnerRequest) Reset() {
	*x = UpdateRunnerRequest{}
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRunnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRunnerRequest) ProtoMessage() {}

func (x *UpdateRunnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRunnerRequest.ProtoReflect.Descriptor instead.
func (*UpdateRunnerRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRunnerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRunnerRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateRunnerRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type UpdateRunnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runner        *Runner                `protobuf:"bytes,1,opt,name=runner,proto3" json:"runner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRunnerResponse) Reset() {
	*x = UpdateRunnerResponse{}
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRunnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRunnerResponse) ProtoMessage() {}

func (x *UpdateRunnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRunnerResponse.ProtoReflect.Descriptor instead.
func (*UpdateRunnerResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateRunnerResponse) GetRunner() *Runner {
	if x != nil {
		return x.Runner
	}
	return nil
}

type DeleteRunnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRunnerRequest) Reset() {
	*x = DeleteRunnerRequest{}
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRunnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRunnerRequest) ProtoMessage() {}

func (x *DeleteRunnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRunnerRequest.ProtoReflect.Descriptor instead.
func (*DeleteRunnerRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRunnerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRunnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRunnerResponse) Reset() {
	*x = DeleteRunnerResponse{}
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRunnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRunnerResponse) ProtoMessage() {}

func (x *DeleteRunnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRunnerResponse.ProtoReflect.Descriptor instead.
func (*DeleteRunnerResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{11}
}

type ValidateServiceTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenHash     string                 `protobuf:"bytes,1,opt,name=token_hash,json=tokenHash,proto3" json:"token_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateServiceTokenRequest) Reset() {
	*x = ValidateServiceTokenRequest{}
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateServiceTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateServiceTokenRequest) ProtoMessage() {}

func (x *ValidateServiceTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateServiceTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateServiceTokenRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{12}
}

func (x *ValidateServiceTokenRequest) GetTokenHash() string {
	if x != nil {
		return x.TokenHash
	}
	return ""
}

type ValidateServiceTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runner        *Runner                `protobuf:"bytes,1,opt,name=runner,proto3" json:"runner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateServiceTokenResponse) Reset() {
	*x = ValidateServiceTokenResponse{}
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateServiceTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateServiceTokenResponse) ProtoMessage() {}

func (x *ValidateServiceTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateServiceTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateServiceTokenResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{13}
}

func (x *ValidateServiceTokenResponse) GetRunner() *Runner {
	if x != nil {
		return x.Runner
	}
	return nil
}

type EnrollRunnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceToken  string                 `protobuf:"bytes,1,opt,name=service_token,json=serviceToken,proto3" json:"service_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRunnerRequest) Reset() {
	*x = EnrollRunnerRequest{}
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRunnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRunnerRequest) ProtoMessage() {}

func (x *EnrollRunnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRunnerRequest.ProtoReflect.Descriptor instead.
func (*EnrollRunnerRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{14}
}

func (x *EnrollRunnerRequest) GetServiceToken() string {
	if x != nil {
		return x.ServiceToken
	}
	return ""
}

type EnrollRunnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityJson  []byte                 `protobuf:"bytes,1,opt,name=identity_json,json=identityJson,proto3" json:"identity_json,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	IdentityId    string                 `protobuf:"bytes,3,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRunnerResponse) Reset() {
	*x = EnrollRunnerResponse{}
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRunnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRunnerResponse) ProtoMessage() {}

func (x *EnrollRunnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRunnerResponse.ProtoReflect.Descriptor instead.
func (*EnrollRunnerResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{15}
}

func (x *EnrollRunnerResponse) GetIdentityJson() []byte {
	if x != nil {
		return x.IdentityJson
	}
	return nil
}

func (x *EnrollRunnerResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *EnrollRunnerResponse) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role          ContainerRole          `protobuf:"varint,3,opt,name=role,proto3,enum=agynio.api.runners.v1.ContainerRole" json:"role,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Status        ContainerStatus        `protobuf:"varint,5,opt,name=status,proto3,enum=agynio.api.runners.v1.ContainerStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{16}
}

func (x *Container) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *Container) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Container) GetRole() ContainerRole {
	if x != nil {
		return x.Role
	}
	return ContainerRole_CONTAINER_ROLE_UNSPECIFIED
}

func (x *Container) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Container) GetStatus() ContainerStatus {
	if x != nil {
		return x.Status
	}
	return ContainerStatus_CONTAINER_STATUS_UNSPECIFIED
}

type Workload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Meta           *EntityMeta            `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	RunnerId       string                 `protobuf:"bytes,2,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	ThreadId       string                 `protobuf:"bytes,3,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	AgentId        string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,5,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Status         WorkloadStatus         `protobuf:"varint,6,opt,name=status,proto3,enum=agynio.api.runners.v1.WorkloadStatus" json:"status,omitempty"`
	Containers     []*Container           `protobuf:"bytes,7,rep,name=containers,proto3" json:"containers,omitempty"`
	ZitiIdentityId string                 `protobuf:"bytes,8,opt,name=ziti_identity_id,json=zitiIdentityId,proto3" json:"ziti_identity_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Workload) Reset() {
	*x = Workload{}
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workload) ProtoMessage() {}

func (x *Workload) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workload.ProtoReflect.Descriptor instead.
func (*Workload) Descriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{17}
}

func (x *Workload) GetMeta() *EntityMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Workload) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *Workload) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *Workload) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Workload) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Workload) GetStatus() WorkloadStatus {
	if x != nil {
		return x.Status
	}
	return WorkloadStatus_WORKLOAD_STATUS_UNSPECIFIED
}

func (x *Workload) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *Workload) GetZitiIdentityId() string {
	if x != nil {
		return x.ZitiIdentityId
	}
	return ""
}

type CreateWorkloadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RunnerId       string                 `protobuf:"bytes,2,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	ThreadId       string                 `protobuf:"bytes,3,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	AgentId        string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,5,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Status         WorkloadStatus         `protobuf:"varint,6,opt,name=status,proto3,enum=agynio.api.runners.v1.WorkloadStatus" json:"status,omitempty"`
	Containers     []*Container           `protobuf:"bytes,7,rep,name=containers,proto3" json:"containers,omitempty"`
	ZitiIdentityId string                 `protobuf:"bytes,8,opt,name=ziti_identity_id,json=zitiIdentityId,proto3" json:"ziti_identity_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateWorkloadRequest) Reset() {
	*x = CreateWorkloadRequest{}
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkloadRequest) ProtoMessage() {}

func (x *CreateWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkloadRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{18}
}

func (x *CreateWorkloadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateWorkloadRequest) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *CreateWorkloadRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *CreateWorkloadRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CreateWorkloadRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateWorkloadRequest) GetStatus() WorkloadStatus {
	if x != nil {
		return x.Status
	}
	return WorkloadStatus_WORKLOAD_STATUS_UNSPECIFIED
}

func (x *CreateWorkloadRequest) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *CreateWorkloadRequest) GetZitiIdentityId() string {
	if x != nil {
		return x.ZitiIdentityId
	}
	return ""
}

type CreateWorkloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workload      *Workload              `protobuf:"bytes,1,opt,name=workload,proto3" json:"workload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkloadResponse) Reset() {
	*x = CreateWorkloadResponse{}
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkloadResponse) ProtoMessage() {}

func (x *CreateWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkloadResponse.ProtoReflect.Descriptor instead.
func (*CreateWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{19}
}

func (x *CreateWorkloadResponse) GetWorkload() *Workload {
	if x != nil {
		return x.Workload
	}
	return nil
}

type UpdateWorkloadStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        WorkloadStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=agynio.api.runners.v1.WorkloadStatus" json:"status,omitempty"`
	Containers    []*Container           `protobuf:"bytes,3,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkloadStatusRequest) Reset() {
	*x = UpdateWorkloadStatusRequest{}
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkloadStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkloadStatusRequest) ProtoMessage() {}

func (x *UpdateWorkloadStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkloadStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkloadStatusRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateWorkloadStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateWorkloadStatusRequest) GetStatus() WorkloadStatus {
	if x != nil {
		return x.Status
	}
	return WorkloadStatus_WORKLOAD_STATUS_UNSPECIFIED
}

func (x *UpdateWorkloadStatusRequest) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

type UpdateWorkloadStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workload      *Workload              `protobuf:"bytes,1,opt,name=workload,proto3" json:"workload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkloadStatusResponse) Reset() {
	*x = UpdateWorkloadStatusResponse{}
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkloadStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkloadStatusResponse) ProtoMessage() {}

func (x *UpdateWorkloadStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkloadStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateWorkloadStatusResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateWorkloadStatusResponse) GetWorkload() *Workload {
	if x != nil {
		return x.Workload
	}
	return nil
}

type DeleteWorkloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkloadRequest) Reset() {
	*x = DeleteWorkloadRequest{}
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkloadRequest) ProtoMessage() {}

func (x *DeleteWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkloadRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteWorkloadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteWorkloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkloadResponse) Reset() {
	*x = DeleteWorkloadResponse{}
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkloadResponse) ProtoMessage() {}

func (x *DeleteWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkloadResponse.ProtoReflect.Descriptor instead.
func (*DeleteWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{23}
}

type GetWorkloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkloadRequest) Reset() {
	*x = GetWorkloadRequest{}
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkloadRequest) ProtoMessage() {}

func (x *GetWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkloadRequest.ProtoReflect.Descriptor instead.
func (*GetWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{24}
}

func (x *GetWorkloadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetWorkloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workload      *Workload              `protobuf:"bytes,1,opt,name=workload,proto3" json:"workload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkloadResponse) Reset() {
	*x = GetWorkloadResponse{}
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkloadResponse) ProtoMessage() {}

func (x *GetWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkloadResponse.ProtoReflect.Descriptor instead.
func (*GetWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{25}
}

func (x *GetWorkloadResponse) GetWorkload() *Workload {
	if x != nil {
		return x.Workload
	}
	return nil
}

type ListWorkloadsByThreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkloadsByThreadRequest) Reset() {
	*x = ListWorkloadsByThreadRequest{}
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkloadsByThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkloadsByThreadRequest) ProtoMessage() {}

func (x *ListWorkloadsByThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkloadsByThreadRequest.ProtoReflect.Descriptor instead.
func (*ListWorkloadsByThreadRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{26}
}

func (x *ListWorkloadsByThreadRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *ListWorkloadsByThreadRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListWorkloadsByThreadRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListWorkloadsByThreadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workloads     []*Workload            `protobuf:"bytes,1,rep,name=workloads,proto3" json:"workloads,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkloadsByThreadResponse) Reset() {
	*x = ListWorkloadsByThreadResponse{}
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkloadsByThreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkloadsByThreadResponse) ProtoMessage() {}

func (x *ListWorkloadsByThreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkloadsByThreadResponse.ProtoReflect.Descriptor instead.
func (*ListWorkloadsByThreadResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{27}
}

func (x *ListWorkloadsByThreadResponse) GetWorkloads() []*Workload {
	if x != nil {
		return x.Workloads
	}
	return nil
}

func (x *ListWorkloadsByThreadResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListWorkloadsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Statuses      []WorkloadStatus       `protobuf:"varint,3,rep,packed,name=statuses,proto3,enum=agynio.api.runners.v1.WorkloadStatus" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkloadsRequest) Reset() {
	*x = ListWorkloadsRequest{}
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkloadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkloadsRequest) ProtoMessage() {}

func (x *ListWorkloadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkloadsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkloadsRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{28}
}

func (x *ListWorkloadsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListWorkloadsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListWorkloadsRequest) GetStatuses() []WorkloadStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type ListWorkloadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workloads     []*Workload            `protobuf:"bytes,1,rep,name=workloads,proto3" json:"workloads,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkloadsResponse) Reset() {
	*x = ListWorkloadsResponse{}
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkloadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkloadsResponse) ProtoMessage() {}

func (x *ListWorkloadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_runners_v1_runners_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkloadsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkloadsResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_runners_v1_runners_proto_rawDescGZIP(), []int{29}
}

func (x *ListWorkloadsResponse) GetWorkloads() []*Workload {
	if x != nil {
		return x.Workloads
	}
	return nil
}

func (x *ListWorkloadsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_agynio_api_runners_v1_runners_proto protoreflect.FileDescriptor

const file_agynio_api_runners_v1_runners_proto_rawDesc = "" +
	"\n" +
	"#agynio/api/runners/v1/runners.proto\x12\x15agynio.api.runners.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x92\x01\n" +
	"\n" +
	"EntityMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa5\x03\n" +
	"\x06Runner\x125\n" +
	"\x04meta\x18\x01 \x01(\v2!.agynio.api.runners.v1.EntityMetaR\x04meta\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\x0forganization_id\x18\x03 \x01(\tH\x00R\x0eorganizationId\x88\x01\x01\x12\x1f\n" +
	"\videntity_id\x18\x04 \x01(\tR\n" +
	"identityId\x12;\n" +
	"\x06status\x18\x05 \x01(\x0e2#.agynio.api.runners.v1.RunnerStatusR\x06status\x12A\n" +
	"\x06labels\x18\x06 \x03(\v2).agynio.api.runners.v1.Runner.LabelsEntryR\x06labels\x122\n" +
	"\x15openziti_service_name\x18\a \x01(\tR\x13openzitiServiceName\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x12\n" +
	"\x10_organization_id\"\xfa\x01\n" +
	"\x15RegisterRunnerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x0forganization_id\x18\x02 \x01(\tH\x00R\x0eorganizationId\x88\x01\x01\x12P\n" +
	"\x06labels\x18\x03 \x03(\v28.agynio.api.runners.v1.RegisterRunnerRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x12\n" +
	"\x10_organization_id\"t\n" +
	"\x16RegisterRunnerResponse\x125\n" +
	"\x06runner\x18\x01 \x01(\v2\x1d.agynio.api.runners.v1.RunnerR\x06runner\x12#\n" +
	"\rservice_token\x18\x02 \x01(\tR\fserviceToken\"\"\n" +
	"\x10GetRunnerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x11GetRunnerResponse\x125\n" +
	"\x06runner\x18\x01 \x01(\v2\x1d.agynio.api.runners.v1.RunnerR\x06runner\"\x92\x01\n" +
	"\x12ListRunnersRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12,\n" +
	"\x0forganization_id\x18\x03 \x01(\tH\x00R\x0eorganizationId\x88\x01\x01B\x12\n" +
	"\x10_organization_id\"v\n" +
	"\x13ListRunnersResponse\x127\n" +
	"\arunners\x18\x01 \x03(\v2\x1d.agynio.api.runners.v1.RunnerR\arunners\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xd2\x01\n" +
	"\x13UpdateRunnerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12N\n" +
	"\x06labels\x18\x03 \x03(\v26.agynio.api.runners.v1.UpdateRunnerRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05_name\"M\n" +
	"\x14UpdateRunnerResponse\x125\n" +
	"\x06runner\x18\x01 \x01(\v2\x1d.agynio.api.runners.v1.RunnerR\x06runner\"%\n" +
	"\x13DeleteRunnerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14DeleteRunnerResponse\"<\n" +
	"\x1bValidateServiceTokenRequest\x12\x1d\n" +
	"\n" +
	"token_hash\x18\x01 \x01(\tR\ttokenHash\"U\n" +
	"\x1cValidateServiceTokenResponse\x125\n" +
	"\x06runner\x18\x01 \x01(\v2\x1d.agynio.api.runners.v1.RunnerR\x06runner\":\n" +
	"\x13EnrollRunnerRequest\x12#\n" +
	"\rservice_token\x18\x01 \x01(\tR\fserviceToken\"\x7f\n" +
	"\x14EnrollRunnerResponse\x12#\n" +
	"\ridentity_json\x18\x01 \x01(\fR\fidentityJson\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x1f\n" +
	"\videntity_id\x18\x03 \x01(\tR\n" +
	"identityId\"\xd2\x01\n" +
	"\tContainer\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x128\n" +
	"\x04role\x18\x03 \x01(\x0e2$.agynio.api.runners.v1.ContainerRoleR\x04role\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12>\n" +
	"\x06status\x18\x05 \x01(\x0e2&.agynio.api.runners.v1.ContainerStatusR\x06status\"\xea\x02\n" +
	"\bWorkload\x125\n" +
	"\x04meta\x18\x01 \x01(\v2!.agynio.api.runners.v1.EntityMetaR\x04meta\x12\x1b\n" +
	"\trunner_id\x18\x02 \x01(\tR\brunnerId\x12\x1b\n" +
	"\tthread_id\x18\x03 \x01(\tR\bthreadId\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x12'\n" +
	"\x0forganization_id\x18\x05 \x01(\tR\x0eorganizationId\x12=\n" +
	"\x06status\x18\x06 \x01(\x0e2%.agynio.api.runners.v1.WorkloadStatusR\x06status\x12@\n" +
	"\n" +
	"containers\x18\a \x03(\v2 .agynio.api.runners.v1.ContainerR\n" +
	"containers\x12(\n" +
	"\x10ziti_identity_id\x18\b \x01(\tR\x0ezitiIdentityId\"\xd0\x02\n" +
	"\x15CreateWorkloadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\trunner_id\x18\x02 \x01(\tR\brunnerId\x12\x1b\n" +
	"\tthread_id\x18\x03 \x01(\tR\bthreadId\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x12'\n" +
	"\x0forganization_id\x18\x05 \x01(\tR\x0eorganizationId\x12=\n" +
	"\x06status\x18\x06 \x01(\x0e2%.agynio.api.runners.v1.WorkloadStatusR\x06status\x12@\n" +
	"\n" +
	"containers\x18\a \x03(\v2 .agynio.api.runners.v1.ContainerR\n" +
	"containers\x12(\n" +
	"\x10ziti_identity_id\x18\b \x01(\tR\x0ezitiIdentityId\"U\n" +
	"\x16CreateWorkloadResponse\x12;\n" +
	"\bworkload\x18\x01 \x01(\v2\x1f.agynio.api.runners.v1.WorkloadR\bworkload\"\xae\x01\n" +
	"\x1bUpdateWorkloadStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12=\n" +
	"\x06status\x18\x02 \x01(\x0e2%.agynio.api.runners.v1.WorkloadStatusR\x06status\x12@\n" +
	"\n" +
	"containers\x18\x03 \x03(\v2 .agynio.api.runners.v1.ContainerR\n" +
	"containers\"[\n" +
	"\x1cUpdateWorkloadStatusResponse\x12;\n" +
	"\bworkload\x18\x01 \x01(\v2\x1f.agynio.api.runners.v1.WorkloadR\bworkload\"'\n" +
	"\x15DeleteWorkloadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16DeleteWorkloadResponse\"$\n" +
	"\x12GetWorkloadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"R\n" +
	"\x13GetWorkloadResponse\x12;\n" +
	"\bworkload\x18\x01 \x01(\v2\x1f.agynio.api.runners.v1.WorkloadR\bworkload\"w\n" +
	"\x1cListWorkloadsByThreadRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x86\x01\n" +
	"\x1dListWorkloadsByThreadResponse\x12=\n" +
	"\tworkloads\x18\x01 \x03(\v2\x1f.agynio.api.runners.v1.WorkloadR\tworkloads\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x95\x01\n" +
	"\x14ListWorkloadsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12A\n" +
	"\bstatuses\x18\x03 \x03(\x0e2%.agynio.api.runners.v1.WorkloadStatusR\bstatuses\"~\n" +
	"\x15ListWorkloadsResponse\x12=\n" +
	"\tworkloads\x18\x01 \x03(\v2\x1f.agynio.api.runners.v1.WorkloadR\tworkloads\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken*\x7f\n" +
	"\fRunnerStatus\x12\x1d\n" +
	"\x19RUNNER_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15RUNNER_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16RUNNER_STATUS_ENROLLED\x10\x02\x12\x19\n" +
	"\x15RUNNER_STATUS_OFFLINE\x10\x03*\xc3\x01\n" +
	"\x0eWorkloadStatus\x12\x1f\n" +
	"\x1bWORKLOAD_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18WORKLOAD_STATUS_STARTING\x10\x01\x12\x1b\n" +
	"\x17WORKLOAD_STATUS_RUNNING\x10\x02\x12\x1c\n" +
	"\x18WORKLOAD_STATUS_STOPPING\x10\x03\x12\x1b\n" +
	"\x17WORKLOAD_STATUS_STOPPED\x10\x04\x12\x1a\n" +
	"\x16WORKLOAD_STATUS_FAILED\x10\x05*}\n" +
	"\rContainerRole\x12\x1e\n" +
	"\x1aCONTAINER_ROLE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CONTAINER_ROLE_MAIN\x10\x01\x12\x1a\n" +
	"\x16CONTAINER_ROLE_SIDECAR\x10\x02\x12\x17\n" +
	"\x13CONTAINER_ROLE_INIT\x10\x03*\x90\x01\n" +
	"\x0fContainerStatus\x12 \n" +
	"\x1cCONTAINER_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CONTAINER_STATUS_RUNNING\x10\x01\x12\x1f\n" +
	"\x1bCONTAINER_STATUS_TERMINATED\x10\x02\x12\x1c\n" +
	"\x18CONTAINER_STATUS_WAITING\x10\x032\xb7\v\n" +
	"\x0eRunnersService\x12m\n" +
	"\x0eRegisterRunner\x12,.agynio.api.runners.v1.RegisterRunnerRequest\x1a-.agynio.api.runners.v1.RegisterRunnerResponse\x12^\n" +
	"\tGetRunner\x12'.agynio.api.runners.v1.GetRunnerRequest\x1a(.agynio.api.runners.v1.GetRunnerResponse\x12d\n" +
	"\vListRunners\x12).agynio.api.runners.v1.ListRunnersRequest\x1a*.agynio.api.runners.v1.ListRunnersResponse\x12g\n" +
	"\fUpdateRunner\x12*.agynio.api.runners.v1.UpdateRunnerRequest\x1a+.agynio.api.runners.v1.UpdateRunnerResponse\x12g\n" +
	"\fDeleteRunner\x12*.agynio.api.runners.v1.DeleteRunnerRequest\x1a+.agynio.api.runners.v1.DeleteRunnerResponse\x12\x7f\n" +
	"\x14ValidateServiceToken\x122.agynio.api.runners.v1.ValidateServiceTokenRequest\x1a3.agynio.api.runners.v1.ValidateServiceTokenResponse\x12g\n" +
	"\fEnrollRunner\x12*.agynio.api.runners.v1.EnrollRunnerRequest\x1a+.agynio.api.runners.v1.EnrollRunnerResponse\x12m\n" +
	"\x0eCreateWorkload\x12,.agynio.api.runners.v1.CreateWorkloadRequest\x1a-.agynio.api.runners.v1.CreateWorkloadResponse\x12\x7f\n" +
	"\x14UpdateWorkloadStatus\x122.agynio.api.runners.v1.UpdateWorkloadStatusRequest\x1a3.agynio.api.runners.v1.UpdateWorkloadStatusResponse\x12m\n" +
	"\x0eDeleteWorkload\x12,.agynio.api.runners.v1.DeleteWorkloadRequest\x1a-.agynio.api.runners.v1.DeleteWorkloadResponse\x12d\n" +
	"\vGetWorkload\x12).agynio.api.runners.v1.GetWorkloadRequest\x1a*.agynio.api.runners.v1.GetWorkloadResponse\x12\x82\x01\n" +
	"\x15ListWorkloadsByThread\x123.agynio.api.runners.v1.ListWorkloadsByThreadRequest\x1a4.agynio.api.runners.v1.ListWorkloadsByThreadResponse\x12j\n" +
	"\rListWorkloads\x12+.agynio.api.runners.v1.ListWorkloadsRequest\x1a,.agynio.api.runners.v1.ListWorkloadsResponseB\xe3\x01\n" +
	"\x19com.agynio.api.runners.v1B\fRunnersProtoP\x01ZAgithub.com/agynio/runners/.gen/go/agynio/api/runners/v1;runnersv1\xa2\x02\x03AAR\xaa\x02\x15Agynio.Api.Runners.V1\xca\x02\x15Agynio\\Api\\Runners\\V1\xe2\x02!Agynio\\Api\\Runners\\V1\\GPBMetadata\xea\x02\x18Agynio::Api::Runners::V1b\x06proto3"

var (
	file_agynio_api_runners_v1_runners_proto_rawDescOnce sync.Once
	file_agynio_api_runners_v1_runners_proto_rawDescData []byte
)

func file_agynio_api_runners_v1_runners_proto_rawDescGZIP() []byte {
	file_agynio_api_runners_v1_runners_proto_rawDescOnce.Do(func() {
		file_agynio_api_runners_v1_runners_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agynio_api_runners_v1_runners_proto_rawDesc), len(file_agynio_api_runners_v1_runners_proto_rawDesc)))
	})
	return file_agynio_api_runners_v1_runners_proto_rawDescData
}

var file_agynio_api_runners_v1_runners_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_agynio_api_runners_v1_runners_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_agynio_api_runners_v1_runners_proto_goTypes = []any{
	(RunnerStatus)(0),                     // 0: agynio.api.runners.v1.RunnerStatus
	(WorkloadStatus)(0),                   // 1: agynio.api.runners.v1.WorkloadStatus
	(ContainerRole)(0),                    // 2: agynio.api.runners.v1.ContainerRole
	(ContainerStatus)(0),                  // 3: agynio.api.runners.v1.ContainerStatus
	(*EntityMeta)(nil),                    // 4: agynio.api.runners.v1.EntityMeta
	(*Runner)(nil),                        // 5: agynio.api.runners.v1.Runner
	(*RegisterRunnerRequest)(nil),         // 6: agynio.api.runners.v1.RegisterRunnerRequest
	(*RegisterRunnerResponse)(nil),        // 7: agynio.api.runners.v1.RegisterRunnerResponse
	(*GetRunnerRequest)(nil),              // 8: agynio.api.runners.v1.GetRunnerRequest
	(*GetRunnerResponse)(nil),             // 9: agynio.api.runners.v1.GetRunnerResponse
	(*ListRunnersRequest)(nil),            // 10: agynio.api.runners.v1.ListRunnersRequest
	(*ListRunnersResponse)(nil),           // 11: agynio.api.runners.v1.ListRunnersResponse
	(*UpdateRunnerRequest)(nil),           // 12: agynio.api.runners.v1.UpdateRunnerRequest
	(*UpdateRunnerResponse)(nil),          // 13: agynio.api.runners.v1.UpdateRunnerResponse
	(*DeleteRunnerRequest)(nil),           // 14: agynio.api.runners.v1.DeleteRunnerRequest
	(*DeleteRunnerResponse)(nil),          // 15: agynio.api.runners.v1.DeleteRunnerResponse
	(*ValidateServiceTokenRequest)(nil),   // 16: agynio.api.runners.v1.ValidateServiceTokenRequest
	(*ValidateServiceTokenResponse)(nil),  // 17: agynio.api.runners.v1.ValidateServiceTokenResponse
	(*EnrollRunnerRequest)(nil),           // 18: agynio.api.runners.v1.EnrollRunnerRequest
	(*EnrollRunnerResponse)(nil),          // 19: agynio.api.runners.v1.EnrollRunnerResponse
	(*Container)(nil),                     // 20: agynio.api.runners.v1.Container
	(*Workload)(nil),                      // 21: agynio.api.runners.v1.Workload
	(*CreateWorkloadRequest)(nil),         // 22: agynio.api.runners.v1.CreateWorkloadRequest
	(*CreateWorkloadResponse)(nil),        // 23: agynio.api.runners.v1.CreateWorkloadResponse
	(*UpdateWorkloadStatusRequest)(nil),   // 24: agynio.api.runners.v1.UpdateWorkloadStatusRequest
	(*UpdateWorkloadStatusResponse)(nil),  // 25: agynio.api.runners.v1.UpdateWorkloadStatusResponse
	(*DeleteWorkloadRequest)(nil),         // 26: agynio.api.runners.v1.DeleteWorkloadRequest
	(*DeleteWorkloadResponse)(nil),        // 27: agynio.api.runners.v1.DeleteWorkloadResponse
	(*GetWorkloadRequest)(nil),            // 28: agynio.api.runners.v1.GetWorkloadRequest
	(*GetWorkloadResponse)(nil),           // 29: agynio.api.runners.v1.GetWorkloadResponse
	(*ListWorkloadsByThreadRequest)(nil),  // 30: agynio.api.runners.v1.ListWorkloadsByThreadRequest
	(*ListWorkloadsByThreadResponse)(nil), // 31: agynio.api.runners.v1.ListWorkloadsByThreadResponse
	(*ListWorkloadsRequest)(nil),          // 32: agynio.api.runners.v1.ListWorkloadsRequest
	(*ListWorkloadsResponse)(nil),         // 33: agynio.api.runners.v1.ListWorkloadsResponse
	nil,                                   // 34: agynio.api.runners.v1.Runner.LabelsEntry
	nil,                                   // 35: agynio.api.runners.v1.RegisterRunnerRequest.LabelsEntry
	nil,                                   // 36: agynio.api.runners.v1.UpdateRunnerRequest.LabelsEntry
	(*timestamppb.Timestamp)(nil),         // 37: google.protobuf.Timestamp
}
var file_agynio_api_runners_v1_runners_proto_depIdxs = []int32{
	37, // 0: agynio.api.runners.v1.EntityMeta.created_at:type_name -> google.protobuf.Timestamp
	37, // 1: agynio.api.runners.v1.EntityMeta.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 2: agynio.api.runners.v1.Runner.meta:type_name -> agynio.api.runners.v1.EntityMeta
	0,  // 3: agynio.api.runners.v1.Runner.status:type_name -> agynio.api.runners.v1.RunnerStatus
	34, // 4: agynio.api.runners.v1.Runner.labels:type_name -> agynio.api.runners.v1.Runner.LabelsEntry
	35, // 5: agynio.api.runners.v1.RegisterRunnerRequest.labels:type_name -> agynio.api.runners.v1.RegisterRunnerRequest.LabelsEntry
	5,  // 6: agynio.api.runners.v1.RegisterRunnerResponse.runner:type_name -> agynio.api.runners.v1.Runner
	5,  // 7: agynio.api.runners.v1.GetRunnerResponse.runner:type_name -> agynio.api.runners.v1.Runner
	5,  // 8: agynio.api.runners.v1.ListRunnersResponse.runners:type_name -> agynio.api.runners.v1.Runner
	36, // 9: agynio.api.runners.v1.UpdateRunnerRequest.labels:type_name -> agynio.api.runners.v1.UpdateRunnerRequest.LabelsEntry
	5,  // 10: agynio.api.runners.v1.UpdateRunnerResponse.runner:type_name -> agynio.api.runners.v1.Runner
	5,  // 11: agynio.api.runners.v1.ValidateServiceTokenResponse.runner:type_name -> agynio.api.runners.v1.Runner
	2,  // 12: agynio.api.runners.v1.Container.role:type_name -> agynio.api.runners.v1.ContainerRole
	3,  // 13: agynio.api.runners.v1.Container.status:type_name -> agynio.api.runners.v1.ContainerStatus
	4,  // 14: agynio.api.runners.v1.Workload.meta:type_name -> agynio.api.runners.v1.EntityMeta
	1,  // 15: agynio.api.runners.v1.Workload.status:type_name -> agynio.api.runners.v1.WorkloadStatus
	20, // 16: agynio.api.runners.v1.Workload.containers:type_name -> agynio.api.runners.v1.Container
	1,  // 17: agynio.api.runners.v1.CreateWorkloadRequest.status:type_name -> agynio.api.runners.v1.WorkloadStatus
	20, // 18: agynio.api.runners.v1.CreateWorkloadRequest.containers:type_name -> agynio.api.runners.v1.Container
	21, // 19: agynio.api.runners.v1.CreateWorkloadResponse.workload:type_name -> agynio.api.runners.v1.Workload
	1,  // 20: agynio.api.runners.v1.UpdateWorkloadStatusRequest.status:type_name -> agynio.api.runners.v1.WorkloadStatus
	20, // 21: agynio.api.runners.v1.UpdateWorkloadStatusRequest.containers:type_name -> agynio.api.runners.v1.Container
	21, // 22: agynio.api.runners.v1.UpdateWorkloadStatusResponse.workload:type_name -> agynio.api.runners.v1.Workload
	21, // 23: agynio.api.runners.v1.GetWorkloadResponse.workload:type_name -> agynio.api.runners.v1.Workload
	21, // 24: agynio.api.runners.v1.ListWorkloadsByThreadResponse.workloads:type_name -> agynio.api.runners.v1.Workload
	1,  // 25: agynio.api.runners.v1.ListWorkloadsRequest.statuses:type_name -> agynio.api.runners.v1.WorkloadStatus
	21, // 26: agynio.api.runners.v1.ListWorkloadsResponse.workloads:type_name -> agynio.api.runners.v1.Workload
	6,  // 27: agynio.api.runners.v1.RunnersService.RegisterRunner:input_type -> agynio.api.runners.v1.RegisterRunnerRequest
	8,  // 28: agynio.api.runners.v1.RunnersService.GetRunner:input_type -> agynio.api.runners.v1.GetRunnerRequest
	10, // 29: agynio.api.runners.v1.RunnersService.ListRunners:input_type -> agynio.api.runners.v1.ListRunnersRequest
	12, // 30: agynio.api.runners.v1.RunnersService.UpdateRunner:input_type -> agynio.api.runners.v1.UpdateRunnerRequest
	14, // 31: agynio.api.runners.v1.RunnersService.DeleteRunner:input_type -> agynio.api.runners.v1.DeleteRunnerRequest
	16, // 32: agynio.api.runners.v1.RunnersService.ValidateServiceToken:input_type -> agynio.api.runners.v1.ValidateServiceTokenRequest
	18, // 33: agynio.api.runners.v1.RunnersService.EnrollRunner:input_type -> agynio.api.runners.v1.EnrollRunnerRequest
	22, // 34: agynio.api.runners.v1.RunnersService.CreateWorkload:input_type -> agynio.api.runners.v1.CreateWorkloadRequest
	24, // 35: agynio.api.runners.v1.RunnersService.UpdateWorkloadStatus:input_type -> agynio.api.runners.v1.UpdateWorkloadStatusRequest
	26, // 36: agynio.api.runners.v1.RunnersService.DeleteWorkload:input_type -> agynio.api.runners.v1.DeleteWorkloadRequest
	28, // 37: agynio.api.runners.v1.RunnersService.GetWorkload:input_type -> agynio.api.runners.v1.GetWorkloadRequest
	30, // 38: agynio.api.runners.v1.RunnersService.ListWorkloadsByThread:input_type -> agynio.api.runners.v1.ListWorkloadsByThreadRequest
	32, // 39: agynio.api.runners.v1.RunnersService.ListWorkloads:input_type -> agynio.api.runners.v1.ListWorkloadsRequest
	7,  // 40: agynio.api.runners.v1.RunnersService.RegisterRunner:output_type -> agynio.api.runners.v1.RegisterRunnerResponse
	9,  // 41: agynio.api.runners.v1.RunnersService.GetRunner:output_type -> agynio.api.runners.v1.GetRunnerResponse
	11, // 42: agynio.api.runners.v1.RunnersService.ListRunners:output_type -> agynio.api.runners.v1.ListRunnersResponse
	13, // 43: agynio.api.runners.v1.RunnersService.UpdateRunner:output_type -> agynio.api.runners.v1.UpdateRunnerResponse
	15, // 44: agynio.api.runners.v1.RunnersService.DeleteRunner:output_type -> agynio.api.runners.v1.DeleteRunnerResponse
	17, // 45: agynio.api.runners.v1.RunnersService.ValidateServiceToken:output_type -> agynio.api.runners.v1.ValidateServiceTokenResponse
	19, // 46: agynio.api.runners.v1.RunnersService.EnrollRunner:output_type -> agynio.api.runners.v1.EnrollRunnerResponse
	23, // 47: agynio.api.runners.v1.RunnersService.CreateWorkload:output_type -> agynio.api.runners.v1.CreateWorkloadResponse
	25, // 48: agynio.api.runners.v1.RunnersService.UpdateWorkloadStatus:output_type -> agynio.api.runners.v1.UpdateWorkloadStatusResponse
	27, // 49: agynio.api.runners.v1.RunnersService.DeleteWorkload:output_type -> agynio.api.runners.v1.DeleteWorkloadResponse
	29, // 50: agynio.api.runners.v1.RunnersService.GetWorkload:output_type -> agynio.api.runners.v1.GetWorkloadResponse
	31, // 51: agynio.api.runners.v1.RunnersService.ListWorkloadsByThread:output_type -> agynio.api.runners.v1.ListWorkloadsByThreadResponse
	33, // 52: agynio.api.runners.v1.RunnersService.ListWorkloads:output_type -> agynio.api.runners.v1.ListWorkloadsResponse
	40, // [40:53] is the sub-list for method output_type
	27, // [27:40] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_agynio_api_runners_v1_runners_proto_init() }
func file_agynio_api_runners_v1_runners_proto_init() {
	if File_agynio_api_runners_v1_runners_proto != nil {
		return
	}
	file_agynio_api_runners_v1_runners_proto_msgTypes[1].OneofWrappers = []any{}
	file_agynio_api_runners_v1_runners_proto_msgTypes[2].OneofWrappers = []any{}
	file_agynio_api_runners_v1_runners_proto_msgTypes[6].OneofWrappers = []any{}
	file_agynio_api_runners_v1_runners_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agynio_api_runners_v1_runners_proto_rawDesc), len(file_agynio_api_runners_v1_runners_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agynio_api_runners_v1_runners_proto_goTypes,
		DependencyIndexes: file_agynio_api_runners_v1_runners_proto_depIdxs,
		EnumInfos:         file_agynio_api_runners_v1_runners_proto_enumTypes,
		MessageInfos:      file_agynio_api_runners_v1_runners_proto_msgTypes,
	}.Build()
	File_agynio_api_runners_v1_runners_proto = out.File
	file_agynio_api_runners_v1_runners_proto_goTypes = nil
	file_agynio_api_runners_v1_runners_proto_depIdxs = nil
}
