// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: agynio/api/runner/v1/runner.proto

package runnerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RunnerService_Ready_FullMethodName                 = "/agynio.api.runner.v1.RunnerService/Ready"
	RunnerService_StartWorkload_FullMethodName         = "/agynio.api.runner.v1.RunnerService/StartWorkload"
	RunnerService_StopWorkload_FullMethodName          = "/agynio.api.runner.v1.RunnerService/StopWorkload"
	RunnerService_RemoveWorkload_FullMethodName        = "/agynio.api.runner.v1.RunnerService/RemoveWorkload"
	RunnerService_InspectWorkload_FullMethodName       = "/agynio.api.runner.v1.RunnerService/InspectWorkload"
	RunnerService_GetWorkloadLabels_FullMethodName     = "/agynio.api.runner.v1.RunnerService/GetWorkloadLabels"
	RunnerService_ListWorkloads_FullMethodName         = "/agynio.api.runner.v1.RunnerService/ListWorkloads"
	RunnerService_FindWorkloadsByLabels_FullMethodName = "/agynio.api.runner.v1.RunnerService/FindWorkloadsByLabels"
	RunnerService_ListWorkloadsByVolume_FullMethodName = "/agynio.api.runner.v1.RunnerService/ListWorkloadsByVolume"
	RunnerService_ListVolumes_FullMethodName           = "/agynio.api.runner.v1.RunnerService/ListVolumes"
	RunnerService_RemoveVolume_FullMethodName          = "/agynio.api.runner.v1.RunnerService/RemoveVolume"
	RunnerService_TouchWorkload_FullMethodName         = "/agynio.api.runner.v1.RunnerService/TouchWorkload"
	RunnerService_PutArchive_FullMethodName            = "/agynio.api.runner.v1.RunnerService/PutArchive"
	RunnerService_StreamWorkloadLogs_FullMethodName    = "/agynio.api.runner.v1.RunnerService/StreamWorkloadLogs"
	RunnerService_StreamEvents_FullMethodName          = "/agynio.api.runner.v1.RunnerService/StreamEvents"
	RunnerService_Exec_FullMethodName                  = "/agynio.api.runner.v1.RunnerService/Exec"
	RunnerService_CancelExecution_FullMethodName       = "/agynio.api.runner.v1.RunnerService/CancelExecution"
)

// RunnerServiceClient is the client API for RunnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RunnerService mirrors the current docker-runner HTTP+WS+SSE surface,
// but replaces unary exec/run with a single streaming-only Exec RPC.
type RunnerServiceClient interface {
	// Health/readiness
	Ready(ctx context.Context, in *ReadyRequest, opts ...grpc.CallOption) (*ReadyResponse, error)
	// Targets (containers today)
	StartWorkload(ctx context.Context, in *StartWorkloadRequest, opts ...grpc.CallOption) (*StartWorkloadResponse, error)
	StopWorkload(ctx context.Context, in *StopWorkloadRequest, opts ...grpc.CallOption) (*StopWorkloadResponse, error)
	RemoveWorkload(ctx context.Context, in *RemoveWorkloadRequest, opts ...grpc.CallOption) (*RemoveWorkloadResponse, error)
	// Minimal inspect surface with EXACT fields required by platform today.
	InspectWorkload(ctx context.Context, in *InspectWorkloadRequest, opts ...grpc.CallOption) (*InspectWorkloadResponse, error)
	GetWorkloadLabels(ctx context.Context, in *GetWorkloadLabelsRequest, opts ...grpc.CallOption) (*GetWorkloadLabelsResponse, error)
	ListWorkloads(ctx context.Context, in *ListWorkloadsRequest, opts ...grpc.CallOption) (*ListWorkloadsResponse, error)
	FindWorkloadsByLabels(ctx context.Context, in *FindWorkloadsByLabelsRequest, opts ...grpc.CallOption) (*FindWorkloadsByLabelsResponse, error)
	ListWorkloadsByVolume(ctx context.Context, in *ListWorkloadsByVolumeRequest, opts ...grpc.CallOption) (*ListWorkloadsByVolumeResponse, error)
	ListVolumes(ctx context.Context, in *ListVolumesRequest, opts ...grpc.CallOption) (*ListVolumesResponse, error)
	RemoveVolume(ctx context.Context, in *RemoveVolumeRequest, opts ...grpc.CallOption) (*RemoveVolumeResponse, error)
	TouchWorkload(ctx context.Context, in *TouchWorkloadRequest, opts ...grpc.CallOption) (*TouchWorkloadResponse, error)
	PutArchive(ctx context.Context, in *PutArchiveRequest, opts ...grpc.CallOption) (*PutArchiveResponse, error)
	// Streaming logs/events (SSE equivalents)
	// StreamWorkloadLogs streams logs for a workload container addressed by container_name.
	// Error/EOF contract (returned via gRPC status codes, not in-band):
	// - NotFound for unknown workload or container
	// - OK when logs are exhausted or the container terminates with the Pod still present
	// - Unavailable when the Pod is deleted mid-stream
	StreamWorkloadLogs(ctx context.Context, in *StreamWorkloadLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamWorkloadLogsResponse], error)
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamEventsResponse], error)
	// Exec (streaming-only; replaces /v1/exec/run and /v1/exec/interactive/ws)
	Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecRequest, ExecResponse], error)
	// Cancellation for a previously started execution_id.
	CancelExecution(ctx context.Context, in *CancelExecutionRequest, opts ...grpc.CallOption) (*CancelExecutionResponse, error)
}

type runnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRunnerServiceClient(cc grpc.ClientConnInterface) RunnerServiceClient {
	return &runnerServiceClient{cc}
}

func (c *runnerServiceClient) Ready(ctx context.Context, in *ReadyRequest, opts ...grpc.CallOption) (*ReadyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadyResponse)
	err := c.cc.Invoke(ctx, RunnerService_Ready_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) StartWorkload(ctx context.Context, in *StartWorkloadRequest, opts ...grpc.CallOption) (*StartWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartWorkloadResponse)
	err := c.cc.Invoke(ctx, RunnerService_StartWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) StopWorkload(ctx context.Context, in *StopWorkloadRequest, opts ...grpc.CallOption) (*StopWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopWorkloadResponse)
	err := c.cc.Invoke(ctx, RunnerService_StopWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) RemoveWorkload(ctx context.Context, in *RemoveWorkloadRequest, opts ...grpc.CallOption) (*RemoveWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveWorkloadResponse)
	err := c.cc.Invoke(ctx, RunnerService_RemoveWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) InspectWorkload(ctx context.Context, in *InspectWorkloadRequest, opts ...grpc.CallOption) (*InspectWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectWorkloadResponse)
	err := c.cc.Invoke(ctx, RunnerService_InspectWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) GetWorkloadLabels(ctx context.Context, in *GetWorkloadLabelsRequest, opts ...grpc.CallOption) (*GetWorkloadLabelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkloadLabelsResponse)
	err := c.cc.Invoke(ctx, RunnerService_GetWorkloadLabels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) ListWorkloads(ctx context.Context, in *ListWorkloadsRequest, opts ...grpc.CallOption) (*ListWorkloadsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkloadsResponse)
	err := c.cc.Invoke(ctx, RunnerService_ListWorkloads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) FindWorkloadsByLabels(ctx context.Context, in *FindWorkloadsByLabelsRequest, opts ...grpc.CallOption) (*FindWorkloadsByLabelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindWorkloadsByLabelsResponse)
	err := c.cc.Invoke(ctx, RunnerService_FindWorkloadsByLabels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) ListWorkloadsByVolume(ctx context.Context, in *ListWorkloadsByVolumeRequest, opts ...grpc.CallOption) (*ListWorkloadsByVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkloadsByVolumeResponse)
	err := c.cc.Invoke(ctx, RunnerService_ListWorkloadsByVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) ListVolumes(ctx context.Context, in *ListVolumesRequest, opts ...grpc.CallOption) (*ListVolumesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVolumesResponse)
	err := c.cc.Invoke(ctx, RunnerService_ListVolumes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) RemoveVolume(ctx context.Context, in *RemoveVolumeRequest, opts ...grpc.CallOption) (*RemoveVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveVolumeResponse)
	err := c.cc.Invoke(ctx, RunnerService_RemoveVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) TouchWorkload(ctx context.Context, in *TouchWorkloadRequest, opts ...grpc.CallOption) (*TouchWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TouchWorkloadResponse)
	err := c.cc.Invoke(ctx, RunnerService_TouchWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) PutArchive(ctx context.Context, in *PutArchiveRequest, opts ...grpc.CallOption) (*PutArchiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutArchiveResponse)
	err := c.cc.Invoke(ctx, RunnerService_PutArchive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) StreamWorkloadLogs(ctx context.Context, in *StreamWorkloadLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamWorkloadLogsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RunnerService_ServiceDesc.Streams[0], RunnerService_StreamWorkloadLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamWorkloadLogsRequest, StreamWorkloadLogsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RunnerService_StreamWorkloadLogsClient = grpc.ServerStreamingClient[StreamWorkloadLogsResponse]

func (c *runnerServiceClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamEventsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RunnerService_ServiceDesc.Streams[1], RunnerService_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, StreamEventsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RunnerService_StreamEventsClient = grpc.ServerStreamingClient[StreamEventsResponse]

func (c *runnerServiceClient) Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecRequest, ExecResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RunnerService_ServiceDesc.Streams[2], RunnerService_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecRequest, ExecResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RunnerService_ExecClient = grpc.BidiStreamingClient[ExecRequest, ExecResponse]

func (c *runnerServiceClient) CancelExecution(ctx context.Context, in *CancelExecutionRequest, opts ...grpc.CallOption) (*CancelExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelExecutionResponse)
	err := c.cc.Invoke(ctx, RunnerService_CancelExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunnerServiceServer is the server API for RunnerService service.
// All implementations should embed UnimplementedRunnerServiceServer
// for forward compatibility.
//
// RunnerService mirrors the current docker-runner HTTP+WS+SSE surface,
// but replaces unary exec/run with a single streaming-only Exec RPC.
type RunnerServiceServer interface {
	// Health/readiness
	Ready(context.Context, *ReadyRequest) (*ReadyResponse, error)
	// Targets (containers today)
	StartWorkload(context.Context, *StartWorkloadRequest) (*StartWorkloadResponse, error)
	StopWorkload(context.Context, *StopWorkloadRequest) (*StopWorkloadResponse, error)
	RemoveWorkload(context.Context, *RemoveWorkloadRequest) (*RemoveWorkloadResponse, error)
	// Minimal inspect surface with EXACT fields required by platform today.
	InspectWorkload(context.Context, *InspectWorkloadRequest) (*InspectWorkloadResponse, error)
	GetWorkloadLabels(context.Context, *GetWorkloadLabelsRequest) (*GetWorkloadLabelsResponse, error)
	ListWorkloads(context.Context, *ListWorkloadsRequest) (*ListWorkloadsResponse, error)
	FindWorkloadsByLabels(context.Context, *FindWorkloadsByLabelsRequest) (*FindWorkloadsByLabelsResponse, error)
	ListWorkloadsByVolume(context.Context, *ListWorkloadsByVolumeRequest) (*ListWorkloadsByVolumeResponse, error)
	ListVolumes(context.Context, *ListVolumesRequest) (*ListVolumesResponse, error)
	RemoveVolume(context.Context, *RemoveVolumeRequest) (*RemoveVolumeResponse, error)
	TouchWorkload(context.Context, *TouchWorkloadRequest) (*TouchWorkloadResponse, error)
	PutArchive(context.Context, *PutArchiveRequest) (*PutArchiveResponse, error)
	// Streaming logs/events (SSE equivalents)
	// StreamWorkloadLogs streams logs for a workload container addressed by container_name.
	// Error/EOF contract (returned via gRPC status codes, not in-band):
	// - NotFound for unknown workload or container
	// - OK when logs are exhausted or the container terminates with the Pod still present
	// - Unavailable when the Pod is deleted mid-stream
	StreamWorkloadLogs(*StreamWorkloadLogsRequest, grpc.ServerStreamingServer[StreamWorkloadLogsResponse]) error
	StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[StreamEventsResponse]) error
	// Exec (streaming-only; replaces /v1/exec/run and /v1/exec/interactive/ws)
	Exec(grpc.BidiStreamingServer[ExecRequest, ExecResponse]) error
	// Cancellation for a previously started execution_id.
	CancelExecution(context.Context, *CancelExecutionRequest) (*CancelExecutionResponse, error)
}

// UnimplementedRunnerServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunnerServiceServer struct{}

func (UnimplementedRunnerServiceServer) Ready(context.Context, *ReadyRequest) (*ReadyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ready not implemented")
}
func (UnimplementedRunnerServiceServer) StartWorkload(context.Context, *StartWorkloadRequest) (*StartWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartWorkload not implemented")
}
func (UnimplementedRunnerServiceServer) StopWorkload(context.Context, *StopWorkloadRequest) (*StopWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopWorkload not implemented")
}
func (UnimplementedRunnerServiceServer) RemoveWorkload(context.Context, *RemoveWorkloadRequest) (*RemoveWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveWorkload not implemented")
}
func (UnimplementedRunnerServiceServer) InspectWorkload(context.Context, *InspectWorkloadRequest) (*InspectWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InspectWorkload not implemented")
}
func (UnimplementedRunnerServiceServer) GetWorkloadLabels(context.Context, *GetWorkloadLabelsRequest) (*GetWorkloadLabelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkloadLabels not implemented")
}
func (UnimplementedRunnerServiceServer) ListWorkloads(context.Context, *ListWorkloadsRequest) (*ListWorkloadsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkloads not implemented")
}
func (UnimplementedRunnerServiceServer) FindWorkloadsByLabels(context.Context, *FindWorkloadsByLabelsRequest) (*FindWorkloadsByLabelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindWorkloadsByLabels not implemented")
}
func (UnimplementedRunnerServiceServer) ListWorkloadsByVolume(context.Context, *ListWorkloadsByVolumeRequest) (*ListWorkloadsByVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkloadsByVolume not implemented")
}
func (UnimplementedRunnerServiceServer) ListVolumes(context.Context, *ListVolumesRequest) (*ListVolumesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVolumes not implemented")
}
func (UnimplementedRunnerServiceServer) RemoveVolume(context.Context, *RemoveVolumeRequest) (*RemoveVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveVolume not implemented")
}
func (UnimplementedRunnerServiceServer) TouchWorkload(context.Context, *TouchWorkloadRequest) (*TouchWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TouchWorkload not implemented")
}
func (UnimplementedRunnerServiceServer) PutArchive(context.Context, *PutArchiveRequest) (*PutArchiveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutArchive not implemented")
}
func (UnimplementedRunnerServiceServer) StreamWorkloadLogs(*StreamWorkloadLogsRequest, grpc.ServerStreamingServer[StreamWorkloadLogsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamWorkloadLogs not implemented")
}
func (UnimplementedRunnerServiceServer) StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[StreamEventsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedRunnerServiceServer) Exec(grpc.BidiStreamingServer[ExecRequest, ExecResponse]) error {
	return status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedRunnerServiceServer) CancelExecution(context.Context, *CancelExecutionRequest) (*CancelExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelExecution not implemented")
}
func (UnimplementedRunnerServiceServer) testEmbeddedByValue() {}

// UnsafeRunnerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunnerServiceServer will
// result in compilation errors.
type UnsafeRunnerServiceServer interface {
	mustEmbedUnimplementedRunnerServiceServer()
}

func RegisterRunnerServiceServer(s grpc.ServiceRegistrar, srv RunnerServiceServer) {
	// If the following call panics, it indicates UnimplementedRunnerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RunnerService_ServiceDesc, srv)
}

func _RunnerService_Ready_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).Ready(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_Ready_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).Ready(ctx, req.(*ReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_StartWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).StartWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_StartWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).StartWorkload(ctx, req.(*StartWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_StopWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).StopWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_StopWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).StopWorkload(ctx, req.(*StopWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_RemoveWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).RemoveWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_RemoveWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).RemoveWorkload(ctx, req.(*RemoveWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_InspectWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).InspectWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_InspectWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).InspectWorkload(ctx, req.(*InspectWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_GetWorkloadLabels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkloadLabelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).GetWorkloadLabels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_GetWorkloadLabels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).GetWorkloadLabels(ctx, req.(*GetWorkloadLabelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_ListWorkloads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkloadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).ListWorkloads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_ListWorkloads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).ListWorkloads(ctx, req.(*ListWorkloadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_FindWorkloadsByLabels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindWorkloadsByLabelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).FindWorkloadsByLabels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_FindWorkloadsByLabels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).FindWorkloadsByLabels(ctx, req.(*FindWorkloadsByLabelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_ListWorkloadsByVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkloadsByVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).ListWorkloadsByVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_ListWorkloadsByVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).ListWorkloadsByVolume(ctx, req.(*ListWorkloadsByVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_ListVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVolumesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).ListVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_ListVolumes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).ListVolumes(ctx, req.(*ListVolumesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_RemoveVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).RemoveVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_RemoveVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).RemoveVolume(ctx, req.(*RemoveVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_TouchWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TouchWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).TouchWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_TouchWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).TouchWorkload(ctx, req.(*TouchWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_PutArchive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutArchiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).PutArchive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_PutArchive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).PutArchive(ctx, req.(*PutArchiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_StreamWorkloadLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamWorkloadLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RunnerServiceServer).StreamWorkloadLogs(m, &grpc.GenericServerStream[StreamWorkloadLogsRequest, StreamWorkloadLogsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RunnerService_StreamWorkloadLogsServer = grpc.ServerStreamingServer[StreamWorkloadLogsResponse]

func _RunnerService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RunnerServiceServer).StreamEvents(m, &grpc.GenericServerStream[StreamEventsRequest, StreamEventsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RunnerService_StreamEventsServer = grpc.ServerStreamingServer[StreamEventsResponse]

func _RunnerService_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RunnerServiceServer).Exec(&grpc.GenericServerStream[ExecRequest, ExecResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RunnerService_ExecServer = grpc.BidiStreamingServer[ExecRequest, ExecResponse]

func _RunnerService_CancelExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).CancelExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_CancelExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).CancelExecution(ctx, req.(*CancelExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RunnerService_ServiceDesc is the grpc.ServiceDesc for RunnerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunnerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agynio.api.runner.v1.RunnerService",
	HandlerType: (*RunnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ready",
			Handler:    _RunnerService_Ready_Handler,
		},
		{
			MethodName: "StartWorkload",
			Handler:    _RunnerService_StartWorkload_Handler,
		},
		{
			MethodName: "StopWorkload",
			Handler:    _RunnerService_StopWorkload_Handler,
		},
		{
			MethodName: "RemoveWorkload",
			Handler:    _RunnerService_RemoveWorkload_Handler,
		},
		{
			MethodName: "InspectWorkload",
			Handler:    _RunnerService_InspectWorkload_Handler,
		},
		{
			MethodName: "GetWorkloadLabels",
			Handler:    _RunnerService_GetWorkloadLabels_Handler,
		},
		{
			MethodName: "ListWorkloads",
			Handler:    _RunnerService_ListWorkloads_Handler,
		},
		{
			MethodName: "FindWorkloadsByLabels",
			Handler:    _RunnerService_FindWorkloadsByLabels_Handler,
		},
		{
			MethodName: "ListWorkloadsByVolume",
			Handler:    _RunnerService_ListWorkloadsByVolume_Handler,
		},
		{
			MethodName: "ListVolumes",
			Handler:    _RunnerService_ListVolumes_Handler,
		},
		{
			MethodName: "RemoveVolume",
			Handler:    _RunnerService_RemoveVolume_Handler,
		},
		{
			MethodName: "TouchWorkload",
			Handler:    _RunnerService_TouchWorkload_Handler,
		},
		{
			MethodName: "PutArchive",
			Handler:    _RunnerService_PutArchive_Handler,
		},
		{
			MethodName: "CancelExecution",
			Handler:    _RunnerService_CancelExecution_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamWorkloadLogs",
			Handler:       _RunnerService_StreamWorkloadLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamEvents",
			Handler:       _RunnerService_StreamEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Exec",
			Handler:       _RunnerService_Exec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agynio/api/runner/v1/runner.proto",
}
