// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agynio/api/authorization/v1/authorization.proto

package authorizationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TupleKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`         // e.g. "identity:user_abc"
	Relation      string                 `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"` // e.g. "owner"
	Object        string                 `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`     // e.g. "organization:org_123"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TupleKey) Reset() {
	*x = TupleKey{}
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TupleKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TupleKey) ProtoMessage() {}

func (x *TupleKey) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TupleKey.ProtoReflect.Descriptor instead.
func (*TupleKey) Descriptor() ([]byte, []int) {
	return file_agynio_api_authorization_v1_authorization_proto_rawDescGZIP(), []int{0}
}

func (x *TupleKey) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *TupleKey) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *TupleKey) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

type Tuple struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *TupleKey              `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tuple) Reset() {
	*x = Tuple{}
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tuple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tuple) ProtoMessage() {}

func (x *Tuple) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tuple.ProtoReflect.Descriptor instead.
func (*Tuple) Descriptor() ([]byte, []int) {
	return file_agynio_api_authorization_v1_authorization_proto_rawDescGZIP(), []int{1}
}

func (x *Tuple) GetKey() *TupleKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Tuple) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TupleKey      *TupleKey              `protobuf:"bytes,1,opt,name=tuple_key,json=tupleKey,proto3" json:"tuple_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_authorization_v1_authorization_proto_rawDescGZIP(), []int{2}
}

func (x *CheckRequest) GetTupleKey() *TupleKey {
	if x != nil {
		return x.TupleKey
	}
	return nil
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_authorization_v1_authorization_proto_rawDescGZIP(), []int{3}
}

func (x *CheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

type BatchCheckItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TupleKey      *TupleKey              `protobuf:"bytes,1,opt,name=tuple_key,json=tupleKey,proto3" json:"tuple_key,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckItem) Reset() {
	*x = BatchCheckItem{}
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckItem) ProtoMessage() {}

func (x *BatchCheckItem) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckItem.ProtoReflect.Descriptor instead.
func (*BatchCheckItem) Descriptor() ([]byte, []int) {
	return file_agynio_api_authorization_v1_authorization_proto_rawDescGZIP(), []int{4}
}

func (x *BatchCheckItem) GetTupleKey() *TupleKey {
	if x != nil {
		return x.TupleKey
	}
	return nil
}

func (x *BatchCheckItem) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type BatchCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checks        []*BatchCheckItem      `protobuf:"bytes,1,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckRequest) Reset() {
	*x = BatchCheckRequest{}
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckRequest) ProtoMessage() {}

func (x *BatchCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckRequest.ProtoReflect.Descriptor instead.
func (*BatchCheckRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_authorization_v1_authorization_proto_rawDescGZIP(), []int{5}
}

func (x *BatchCheckRequest) GetChecks() []*BatchCheckItem {
	if x != nil {
		return x.Checks
	}
	return nil
}

type BatchCheckResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckResult) Reset() {
	*x = BatchCheckResult{}
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckResult) ProtoMessage() {}

func (x *BatchCheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckResult.ProtoReflect.Descriptor instead.
func (*BatchCheckResult) Descriptor() ([]byte, []int) {
	return file_agynio_api_authorization_v1_authorization_proto_rawDescGZIP(), []int{6}
}

func (x *BatchCheckResult) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *BatchCheckResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BatchCheckResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Results       map[string]*BatchCheckResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckResponse) Reset() {
	*x = BatchCheckResponse{}
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckResponse) ProtoMessage() {}

func (x *BatchCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckResponse.ProtoReflect.Descriptor instead.
func (*BatchCheckResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_authorization_v1_authorization_proto_rawDescGZIP(), []int{7}
}

func (x *BatchCheckResponse) GetResults() map[string]*BatchCheckResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Writes        []*TupleKey            `protobuf:"bytes,1,rep,name=writes,proto3" json:"writes,omitempty"`
	Deletes       []*TupleKey            `protobuf:"bytes,2,rep,name=deletes,proto3" json:"deletes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_authorization_v1_authorization_proto_rawDescGZIP(), []int{8}
}

func (x *WriteRequest) GetWrites() []*TupleKey {
	if x != nil {
		return x.Writes
	}
	return nil
}

func (x *WriteRequest) GetDeletes() []*TupleKey {
	if x != nil {
		return x.Deletes
	}
	return nil
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_authorization_v1_authorization_proto_rawDescGZIP(), []int{9}
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TupleKey      *TupleKey              `protobuf:"bytes,1,opt,name=tuple_key,json=tupleKey,proto3" json:"tuple_key,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_authorization_v1_authorization_proto_rawDescGZIP(), []int{10}
}

func (x *ReadRequest) GetTupleKey() *TupleKey {
	if x != nil {
		return x.TupleKey
	}
	return nil
}

func (x *ReadRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ReadRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tuples        []*Tuple               `protobuf:"bytes,1,rep,name=tuples,proto3" json:"tuples,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_authorization_v1_authorization_proto_rawDescGZIP(), []int{11}
}

func (x *ReadResponse) GetTuples() []*Tuple {
	if x != nil {
		return x.Tuples
	}
	return nil
}

func (x *ReadResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListObjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`         // e.g. "organization"
	Relation      string                 `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"` // e.g. "member"
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`         // e.g. "identity:user_abc"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObjectsRequest) Reset() {
	*x = ListObjectsRequest{}
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsRequest) ProtoMessage() {}

func (x *ListObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsRequest.ProtoReflect.Descriptor instead.
func (*ListObjectsRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_authorization_v1_authorization_proto_rawDescGZIP(), []int{12}
}

func (x *ListObjectsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListObjectsRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *ListObjectsRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type ListObjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []string               `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"` // e.g. ["organization:org_123"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObjectsResponse) Reset() {
	*x = ListObjectsResponse{}
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsResponse) ProtoMessage() {}

func (x *ListObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsResponse.ProtoReflect.Descriptor instead.
func (*ListObjectsResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_authorization_v1_authorization_proto_rawDescGZIP(), []int{13}
}

func (x *ListObjectsResponse) GetObjects() []string {
	if x != nil {
		return x.Objects
	}
	return nil
}

type UserTypeFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`         // e.g. "identity"
	Relation      string                 `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"` // optional, for usersets
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTypeFilter) Reset() {
	*x = UserTypeFilter{}
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTypeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTypeFilter) ProtoMessage() {}

func (x *UserTypeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTypeFilter.ProtoReflect.Descriptor instead.
func (*UserTypeFilter) Descriptor() ([]byte, []int) {
	return file_agynio_api_authorization_v1_authorization_proto_rawDescGZIP(), []int{14}
}

func (x *UserTypeFilter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UserTypeFilter) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        string                 `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`                              // e.g. "organization:org_123"
	Relation      string                 `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`                          // e.g. "member"
	UserFilters   []*UserTypeFilter      `protobuf:"bytes,3,rep,name=user_filters,json=userFilters,proto3" json:"user_filters,omitempty"` // at least one required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_authorization_v1_authorization_proto_rawDescGZIP(), []int{15}
}

func (x *ListUsersRequest) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ListUsersRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *ListUsersRequest) GetUserFilters() []*UserTypeFilter {
	if x != nil {
		return x.UserFilters
	}
	return nil
}

type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to User:
	//
	//	*User_Object
	//	*User_Wildcard
	User          isUser_User `protobuf_oneof:"user"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_agynio_api_authorization_v1_authorization_proto_rawDescGZIP(), []int{16}
}

func (x *User) GetUser() isUser_User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *User) GetObject() string {
	if x != nil {
		if x, ok := x.User.(*User_Object); ok {
			return x.Object
		}
	}
	return ""
}

func (x *User) GetWildcard() string {
	if x != nil {
		if x, ok := x.User.(*User_Wildcard); ok {
			return x.Wildcard
		}
	}
	return ""
}

type isUser_User interface {
	isUser_User()
}

type User_Object struct {
	Object string `protobuf:"bytes,1,opt,name=object,proto3,oneof"` // e.g. "identity:user_abc"
}

type User_Wildcard struct {
	Wildcard string `protobuf:"bytes,2,opt,name=wildcard,proto3,oneof"` // e.g. "identity:*"
}

func (*User_Object) isUser_User() {}

func (*User_Wildcard) isUser_User() {}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_authorization_v1_authorization_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_authorization_v1_authorization_proto_rawDescGZIP(), []int{17}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_agynio_api_authorization_v1_authorization_proto protoreflect.FileDescriptor

const file_agynio_api_authorization_v1_authorization_proto_rawDesc = "" +
	"\n" +
	"/agynio/api/authorization/v1/authorization.proto\x12\x1bagynio.api.authorization.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"R\n" +
	"\bTupleKey\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x1a\n" +
	"\brelation\x18\x02 \x01(\tR\brelation\x12\x16\n" +
	"\x06object\x18\x03 \x01(\tR\x06object\"z\n" +
	"\x05Tuple\x127\n" +
	"\x03key\x18\x01 \x01(\v2%.agynio.api.authorization.v1.TupleKeyR\x03key\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"R\n" +
	"\fCheckRequest\x12B\n" +
	"\ttuple_key\x18\x01 \x01(\v2%.agynio.api.authorization.v1.TupleKeyR\btupleKey\")\n" +
	"\rCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\"{\n" +
	"\x0eBatchCheckItem\x12B\n" +
	"\ttuple_key\x18\x01 \x01(\v2%.agynio.api.authorization.v1.TupleKeyR\btupleKey\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\"X\n" +
	"\x11BatchCheckRequest\x12C\n" +
	"\x06checks\x18\x01 \x03(\v2+.agynio.api.authorization.v1.BatchCheckItemR\x06checks\"B\n" +
	"\x10BatchCheckResult\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xd7\x01\n" +
	"\x12BatchCheckResponse\x12V\n" +
	"\aresults\x18\x01 \x03(\v2<.agynio.api.authorization.v1.BatchCheckResponse.ResultsEntryR\aresults\x1ai\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12C\n" +
	"\x05value\x18\x02 \x01(\v2-.agynio.api.authorization.v1.BatchCheckResultR\x05value:\x028\x01\"\x8e\x01\n" +
	"\fWriteRequest\x12=\n" +
	"\x06writes\x18\x01 \x03(\v2%.agynio.api.authorization.v1.TupleKeyR\x06writes\x12?\n" +
	"\adeletes\x18\x02 \x03(\v2%.agynio.api.authorization.v1.TupleKeyR\adeletes\"\x0f\n" +
	"\rWriteResponse\"\x8d\x01\n" +
	"\vReadRequest\x12B\n" +
	"\ttuple_key\x18\x01 \x01(\v2%.agynio.api.authorization.v1.TupleKeyR\btupleKey\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"r\n" +
	"\fReadResponse\x12:\n" +
	"\x06tuples\x18\x01 \x03(\v2\".agynio.api.authorization.v1.TupleR\x06tuples\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"X\n" +
	"\x12ListObjectsRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\brelation\x18\x02 \x01(\tR\brelation\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\"/\n" +
	"\x13ListObjectsResponse\x12\x18\n" +
	"\aobjects\x18\x01 \x03(\tR\aobjects\"@\n" +
	"\x0eUserTypeFilter\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\brelation\x18\x02 \x01(\tR\brelation\"\x96\x01\n" +
	"\x10ListUsersRequest\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x12\x1a\n" +
	"\brelation\x18\x02 \x01(\tR\brelation\x12N\n" +
	"\fuser_filters\x18\x03 \x03(\v2+.agynio.api.authorization.v1.UserTypeFilterR\vuserFilters\"F\n" +
	"\x04User\x12\x18\n" +
	"\x06object\x18\x01 \x01(\tH\x00R\x06object\x12\x1c\n" +
	"\bwildcard\x18\x02 \x01(\tH\x00R\bwildcardB\x06\n" +
	"\x04user\"L\n" +
	"\x11ListUsersResponse\x127\n" +
	"\x05users\x18\x01 \x03(\v2!.agynio.api.authorization.v1.UserR\x05users2\x80\x05\n" +
	"\x14AuthorizationService\x12^\n" +
	"\x05Check\x12).agynio.api.authorization.v1.CheckRequest\x1a*.agynio.api.authorization.v1.CheckResponse\x12m\n" +
	"\n" +
	"BatchCheck\x12..agynio.api.authorization.v1.BatchCheckRequest\x1a/.agynio.api.authorization.v1.BatchCheckResponse\x12^\n" +
	"\x05Write\x12).agynio.api.authorization.v1.WriteRequest\x1a*.agynio.api.authorization.v1.WriteResponse\x12[\n" +
	"\x04Read\x12(.agynio.api.authorization.v1.ReadRequest\x1a).agynio.api.authorization.v1.ReadResponse\x12p\n" +
	"\vListObjects\x12/.agynio.api.authorization.v1.ListObjectsRequest\x1a0.agynio.api.authorization.v1.ListObjectsResponse\x12j\n" +
	"\tListUsers\x12-.agynio.api.authorization.v1.ListUsersRequest\x1a..agynio.api.authorization.v1.ListUsersResponseB\x93\x02\n" +
	"\x1fcom.agynio.api.authorization.v1B\x12AuthorizationProtoP\x01ZMgithub.com/agynio/runners/.gen/go/agynio/api/authorization/v1;authorizationv1\xa2\x02\x03AAA\xaa\x02\x1bAgynio.Api.Authorization.V1\xca\x02\x1bAgynio\\Api\\Authorization\\V1\xe2\x02'Agynio\\Api\\Authorization\\V1\\GPBMetadata\xea\x02\x1eAgynio::Api::Authorization::V1b\x06proto3"

var (
	file_agynio_api_authorization_v1_authorization_proto_rawDescOnce sync.Once
	file_agynio_api_authorization_v1_authorization_proto_rawDescData []byte
)

func file_agynio_api_authorization_v1_authorization_proto_rawDescGZIP() []byte {
	file_agynio_api_authorization_v1_authorization_proto_rawDescOnce.Do(func() {
		file_agynio_api_authorization_v1_authorization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agynio_api_authorization_v1_authorization_proto_rawDesc), len(file_agynio_api_authorization_v1_authorization_proto_rawDesc)))
	})
	return file_agynio_api_authorization_v1_authorization_proto_rawDescData
}

var file_agynio_api_authorization_v1_authorization_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_agynio_api_authorization_v1_authorization_proto_goTypes = []any{
	(*TupleKey)(nil),              // 0: agynio.api.authorization.v1.TupleKey
	(*Tuple)(nil),                 // 1: agynio.api.authorization.v1.Tuple
	(*CheckRequest)(nil),          // 2: agynio.api.authorization.v1.CheckRequest
	(*CheckResponse)(nil),         // 3: agynio.api.authorization.v1.CheckResponse
	(*BatchCheckItem)(nil),        // 4: agynio.api.authorization.v1.BatchCheckItem
	(*BatchCheckRequest)(nil),     // 5: agynio.api.authorization.v1.BatchCheckRequest
	(*BatchCheckResult)(nil),      // 6: agynio.api.authorization.v1.BatchCheckResult
	(*BatchCheckResponse)(nil),    // 7: agynio.api.authorization.v1.BatchCheckResponse
	(*WriteRequest)(nil),          // 8: agynio.api.authorization.v1.WriteRequest
	(*WriteResponse)(nil),         // 9: agynio.api.authorization.v1.WriteResponse
	(*ReadRequest)(nil),           // 10: agynio.api.authorization.v1.ReadRequest
	(*ReadResponse)(nil),          // 11: agynio.api.authorization.v1.ReadResponse
	(*ListObjectsRequest)(nil),    // 12: agynio.api.authorization.v1.ListObjectsRequest
	(*ListObjectsResponse)(nil),   // 13: agynio.api.authorization.v1.ListObjectsResponse
	(*UserTypeFilter)(nil),        // 14: agynio.api.authorization.v1.UserTypeFilter
	(*ListUsersRequest)(nil),      // 15: agynio.api.authorization.v1.ListUsersRequest
	(*User)(nil),                  // 16: agynio.api.authorization.v1.User
	(*ListUsersResponse)(nil),     // 17: agynio.api.authorization.v1.ListUsersResponse
	nil,                           // 18: agynio.api.authorization.v1.BatchCheckResponse.ResultsEntry
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
}
var file_agynio_api_authorization_v1_authorization_proto_depIdxs = []int32{
	0,  // 0: agynio.api.authorization.v1.Tuple.key:type_name -> agynio.api.authorization.v1.TupleKey
	19, // 1: agynio.api.authorization.v1.Tuple.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 2: agynio.api.authorization.v1.CheckRequest.tuple_key:type_name -> agynio.api.authorization.v1.TupleKey
	0,  // 3: agynio.api.authorization.v1.BatchCheckItem.tuple_key:type_name -> agynio.api.authorization.v1.TupleKey
	4,  // 4: agynio.api.authorization.v1.BatchCheckRequest.checks:type_name -> agynio.api.authorization.v1.BatchCheckItem
	18, // 5: agynio.api.authorization.v1.BatchCheckResponse.results:type_name -> agynio.api.authorization.v1.BatchCheckResponse.ResultsEntry
	0,  // 6: agynio.api.authorization.v1.WriteRequest.writes:type_name -> agynio.api.authorization.v1.TupleKey
	0,  // 7: agynio.api.authorization.v1.WriteRequest.deletes:type_name -> agynio.api.authorization.v1.TupleKey
	0,  // 8: agynio.api.authorization.v1.ReadRequest.tuple_key:type_name -> agynio.api.authorization.v1.TupleKey
	1,  // 9: agynio.api.authorization.v1.ReadResponse.tuples:type_name -> agynio.api.authorization.v1.Tuple
	14, // 10: agynio.api.authorization.v1.ListUsersRequest.user_filters:type_name -> agynio.api.authorization.v1.UserTypeFilter
	16, // 11: agynio.api.authorization.v1.ListUsersResponse.users:type_name -> agynio.api.authorization.v1.User
	6,  // 12: agynio.api.authorization.v1.BatchCheckResponse.ResultsEntry.value:type_name -> agynio.api.authorization.v1.BatchCheckResult
	2,  // 13: agynio.api.authorization.v1.AuthorizationService.Check:input_type -> agynio.api.authorization.v1.CheckRequest
	5,  // 14: agynio.api.authorization.v1.AuthorizationService.BatchCheck:input_type -> agynio.api.authorization.v1.BatchCheckRequest
	8,  // 15: agynio.api.authorization.v1.AuthorizationService.Write:input_type -> agynio.api.authorization.v1.WriteRequest
	10, // 16: agynio.api.authorization.v1.AuthorizationService.Read:input_type -> agynio.api.authorization.v1.ReadRequest
	12, // 17: agynio.api.authorization.v1.AuthorizationService.ListObjects:input_type -> agynio.api.authorization.v1.ListObjectsRequest
	15, // 18: agynio.api.authorization.v1.AuthorizationService.ListUsers:input_type -> agynio.api.authorization.v1.ListUsersRequest
	3,  // 19: agynio.api.authorization.v1.AuthorizationService.Check:output_type -> agynio.api.authorization.v1.CheckResponse
	7,  // 20: agynio.api.authorization.v1.AuthorizationService.BatchCheck:output_type -> agynio.api.authorization.v1.BatchCheckResponse
	9,  // 21: agynio.api.authorization.v1.AuthorizationService.Write:output_type -> agynio.api.authorization.v1.WriteResponse
	11, // 22: agynio.api.authorization.v1.AuthorizationService.Read:output_type -> agynio.api.authorization.v1.ReadResponse
	13, // 23: agynio.api.authorization.v1.AuthorizationService.ListObjects:output_type -> agynio.api.authorization.v1.ListObjectsResponse
	17, // 24: agynio.api.authorization.v1.AuthorizationService.ListUsers:output_type -> agynio.api.authorization.v1.ListUsersResponse
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_agynio_api_authorization_v1_authorization_proto_init() }
func file_agynio_api_authorization_v1_authorization_proto_init() {
	if File_agynio_api_authorization_v1_authorization_proto != nil {
		return
	}
	file_agynio_api_authorization_v1_authorization_proto_msgTypes[16].OneofWrappers = []any{
		(*User_Object)(nil),
		(*User_Wildcard)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agynio_api_authorization_v1_authorization_proto_rawDesc), len(file_agynio_api_authorization_v1_authorization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agynio_api_authorization_v1_authorization_proto_goTypes,
		DependencyIndexes: file_agynio_api_authorization_v1_authorization_proto_depIdxs,
		MessageInfos:      file_agynio_api_authorization_v1_authorization_proto_msgTypes,
	}.Build()
	File_agynio_api_authorization_v1_authorization_proto = out.File
	file_agynio_api_authorization_v1_authorization_proto_goTypes = nil
	file_agynio_api_authorization_v1_authorization_proto_depIdxs = nil
}
