// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agynio/api/notifications/v1/notifications.proto

package notificationsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope emitted to subscribers and used as the canonical notification.
type NotificationEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`           // server-generated UUID v4
	Ts            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`           // server-generated acceptance time
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`   // origin (e.g., "platform-server")
	Event         string                 `protobuf:"bytes,4,opt,name=event,proto3" json:"event,omitempty"`     // stable event name
	Rooms         []string               `protobuf:"bytes,5,rep,name=rooms,proto3" json:"rooms,omitempty"`     // target rooms (non-empty)
	Payload       *structpb.Struct       `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"` // JSON payload (event-specific schema)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationEnvelope) Reset() {
	*x = NotificationEnvelope{}
	mi := &file_agynio_api_notifications_v1_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationEnvelope) ProtoMessage() {}

func (x *NotificationEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_notifications_v1_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationEnvelope.ProtoReflect.Descriptor instead.
func (*NotificationEnvelope) Descriptor() ([]byte, []int) {
	return file_agynio_api_notifications_v1_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationEnvelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotificationEnvelope) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *NotificationEnvelope) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *NotificationEnvelope) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *NotificationEnvelope) GetRooms() []string {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *NotificationEnvelope) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Rooms         []string               `protobuf:"bytes,2,rep,name=rooms,proto3" json:"rooms,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_agynio_api_notifications_v1_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_notifications_v1_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_notifications_v1_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *PublishRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *PublishRequest) GetRooms() []string {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *PublishRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PublishRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_agynio_api_notifications_v1_notifications_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_notifications_v1_notifications_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_notifications_v1_notifications_proto_rawDescGZIP(), []int{2}
}

func (x *PublishResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublishResponse) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []string               `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_agynio_api_notifications_v1_notifications_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_notifications_v1_notifications_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_notifications_v1_notifications_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeRequest) GetRooms() []string {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *NotificationEnvelope  `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_agynio_api_notifications_v1_notifications_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_notifications_v1_notifications_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_notifications_v1_notifications_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeResponse) GetEnvelope() *NotificationEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

var File_agynio_api_notifications_v1_notifications_proto protoreflect.FileDescriptor

const file_agynio_api_notifications_v1_notifications_proto_rawDesc = "" +
	"\n" +
	"/agynio/api/notifications/v1/notifications.proto\x12\x1bagynio.api.notifications.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc9\x01\n" +
	"\x14NotificationEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x02ts\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x14\n" +
	"\x05event\x18\x04 \x01(\tR\x05event\x12\x14\n" +
	"\x05rooms\x18\x05 \x03(\tR\x05rooms\x121\n" +
	"\apayload\x18\x06 \x01(\v2\x17.google.protobuf.StructR\apayload\"\x87\x01\n" +
	"\x0ePublishRequest\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12\x14\n" +
	"\x05rooms\x18\x02 \x03(\tR\x05rooms\x121\n" +
	"\apayload\x18\x03 \x01(\v2\x17.google.protobuf.StructR\apayload\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"M\n" +
	"\x0fPublishResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x02ts\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\"(\n" +
	"\x10SubscribeRequest\x12\x14\n" +
	"\x05rooms\x18\x01 \x03(\tR\x05rooms\"b\n" +
	"\x11SubscribeResponse\x12M\n" +
	"\benvelope\x18\x01 \x01(\v21.agynio.api.notifications.v1.NotificationEnvelopeR\benvelope2\xea\x01\n" +
	"\x14NotificationsService\x12d\n" +
	"\aPublish\x12+.agynio.api.notifications.v1.PublishRequest\x1a,.agynio.api.notifications.v1.PublishResponse\x12l\n" +
	"\tSubscribe\x12-.agynio.api.notifications.v1.SubscribeRequest\x1a..agynio.api.notifications.v1.SubscribeResponse0\x01B\x93\x02\n" +
	"\x1fcom.agynio.api.notifications.v1B\x12NotificationsProtoP\x01ZMgithub.com/agynio/runners/.gen/go/agynio/api/notifications/v1;notificationsv1\xa2\x02\x03AAN\xaa\x02\x1bAgynio.Api.Notifications.V1\xca\x02\x1bAgynio\\Api\\Notifications\\V1\xe2\x02'Agynio\\Api\\Notifications\\V1\\GPBMetadata\xea\x02\x1eAgynio::Api::Notifications::V1b\x06proto3"

var (
	file_agynio_api_notifications_v1_notifications_proto_rawDescOnce sync.Once
	file_agynio_api_notifications_v1_notifications_proto_rawDescData []byte
)

func file_agynio_api_notifications_v1_notifications_proto_rawDescGZIP() []byte {
	file_agynio_api_notifications_v1_notifications_proto_rawDescOnce.Do(func() {
		file_agynio_api_notifications_v1_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agynio_api_notifications_v1_notifications_proto_rawDesc), len(file_agynio_api_notifications_v1_notifications_proto_rawDesc)))
	})
	return file_agynio_api_notifications_v1_notifications_proto_rawDescData
}

var file_agynio_api_notifications_v1_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_agynio_api_notifications_v1_notifications_proto_goTypes = []any{
	(*NotificationEnvelope)(nil),  // 0: agynio.api.notifications.v1.NotificationEnvelope
	(*PublishRequest)(nil),        // 1: agynio.api.notifications.v1.PublishRequest
	(*PublishResponse)(nil),       // 2: agynio.api.notifications.v1.PublishResponse
	(*SubscribeRequest)(nil),      // 3: agynio.api.notifications.v1.SubscribeRequest
	(*SubscribeResponse)(nil),     // 4: agynio.api.notifications.v1.SubscribeResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 6: google.protobuf.Struct
}
var file_agynio_api_notifications_v1_notifications_proto_depIdxs = []int32{
	5, // 0: agynio.api.notifications.v1.NotificationEnvelope.ts:type_name -> google.protobuf.Timestamp
	6, // 1: agynio.api.notifications.v1.NotificationEnvelope.payload:type_name -> google.protobuf.Struct
	6, // 2: agynio.api.notifications.v1.PublishRequest.payload:type_name -> google.protobuf.Struct
	5, // 3: agynio.api.notifications.v1.PublishResponse.ts:type_name -> google.protobuf.Timestamp
	0, // 4: agynio.api.notifications.v1.SubscribeResponse.envelope:type_name -> agynio.api.notifications.v1.NotificationEnvelope
	1, // 5: agynio.api.notifications.v1.NotificationsService.Publish:input_type -> agynio.api.notifications.v1.PublishRequest
	3, // 6: agynio.api.notifications.v1.NotificationsService.Subscribe:input_type -> agynio.api.notifications.v1.SubscribeRequest
	2, // 7: agynio.api.notifications.v1.NotificationsService.Publish:output_type -> agynio.api.notifications.v1.PublishResponse
	4, // 8: agynio.api.notifications.v1.NotificationsService.Subscribe:output_type -> agynio.api.notifications.v1.SubscribeResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_agynio_api_notifications_v1_notifications_proto_init() }
func file_agynio_api_notifications_v1_notifications_proto_init() {
	if File_agynio_api_notifications_v1_notifications_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agynio_api_notifications_v1_notifications_proto_rawDesc), len(file_agynio_api_notifications_v1_notifications_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agynio_api_notifications_v1_notifications_proto_goTypes,
		DependencyIndexes: file_agynio_api_notifications_v1_notifications_proto_depIdxs,
		MessageInfos:      file_agynio_api_notifications_v1_notifications_proto_msgTypes,
	}.Build()
	File_agynio_api_notifications_v1_notifications_proto = out.File
	file_agynio_api_notifications_v1_notifications_proto_goTypes = nil
	file_agynio_api_notifications_v1_notifications_proto_depIdxs = nil
}
